const techniques=
[
 {
   "ID": 0,
   "Name": "Fire Tower",
   "Power": 155,
   "MP": 27,
   "Invincible Time": 26,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "STUN",
   "Accuracy": 55,
   "Effect Chance": 8,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": 3,
   "First": "25%",
   "Second": "16%",
   "Third": "11%"
 },
 {
   "ID": 1,
   "Name": "Prominence Beam",
   "Power": 444,
   "MP": 61,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "FLAT",
   "Accuracy": 75,
   "Effect Chance": 3,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 6,
   "First": "17%",
   "Second": "10%",
   "Third": "5%"
 },
 {
   "ID": 2,
   "Name": "Spit Fire",
   "Power": 66,
   "MP": 10,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 43,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 1,
   "First": "30%",
   "Second": "22%",
   "Third": "15%"
 },
 {
   "ID": 3,
   "Name": "Red Inferno",
   "Power": 210,
   "MP": 57,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 72,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 5,
   "First": "20%",
   "Second": "12%",
   "Third": "7%"
 },
 {
   "ID": 4,
   "Name": "Magma Bomb",
   "Power": 279,
   "MP": 44,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "CONFUSE",
   "Accuracy": 50,
   "Effect Chance": 4,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 4,
   "First": "22%",
   "Second": "14%",
   "Third": "9%"
 },
 {
   "ID": 5,
   "Name": "Heat Laser",
   "Power": 84,
   "MP": 35,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "FIRE",
   "Effect": "FLAT",
   "Accuracy": 80,
   "Effect Chance": 32,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 2,
   "First": "28%",
   "Second": "19%",
   "Third": "13%"
 },
 {
   "ID": 6,
   "Name": "Inifinity Burn",
   "Power": 488,
   "MP": 88,
   "Invincible Time": 26,
   "Range": "WIDE",
   "Type": "FIRE",
   "Effect": "STUN",
   "Accuracy": 79,
   "Effect Chance": 11,
   "Unknown1": 3,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 7,
   "First": "15%",
   "Second": "8%",
   "Third": "0%"
 },
 {
   "ID": 7,
   "Name": "Meltdown",
   "Power": 400,
   "MP": 106,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "FIRE",
   "Effect": "STUN",
   "Accuracy": 86,
   "Effect Chance": 24,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 8,
   "First": "14%",
   "Second": "6%",
   "Third": "0%"
 },
 {
   "ID": 8,
   "Name": "Thunder Justice",
   "Power": 586,
   "MP": 110,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "STUN",
   "Accuracy": 85,
   "Effect Chance": 32,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 7,
   "First": "13%",
   "Second": "9%",
   "Third": "0%"
 },
 {
   "ID": 9,
   "Name": "Spinning Shot",
   "Power": 389,
   "MP": 50,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 77,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 4,
   "First": "22%",
   "Second": "14%",
   "Third": "10%"
 },
 {
   "ID": 10,
   "Name": "Electric Cloud",
   "Power": 120,
   "MP": 23,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "STUN",
   "Accuracy": 60,
   "Effect Chance": 9,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 92,
   "AI Target Distance": 12,
   "Unused": 0,
   "Tier": 2,
   "First": "32%",
   "Second": "19%",
   "Third": "15%"
 },
 {
   "ID": 11,
   "Name": "Megalo Spark",
   "Power": 382,
   "MP": 58,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "STUN",
   "Accuracy": 68,
   "Effect Chance": 23,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 5,
   "First": "18%",
   "Second": "13%",
   "Third": "8%"
 },
 {
   "ID": 12,
   "Name": "Static Elect",
   "Power": 85,
   "MP": 15,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "AIR",
   "Effect": "STUN",
   "Accuracy": 55,
   "Effect Chance": 15,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 1,
   "First": "36%",
   "Second": "21%",
   "Third": "17%"
 },
 {
   "ID": 13,
   "Name": "Wind Cutter",
   "Power": 178,
   "MP": 31,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 62,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 3,
   "First": "26%",
   "Second": "16%",
   "Third": "13%"
 },
 {
   "ID": 14,
   "Name": "Confused Storm",
   "Power": 225,
   "MP": 72,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "AIR",
   "Effect": "CONFUSE",
   "Accuracy": 87,
   "Effect Chance": 60,
   "Unknown1": 3,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 6,
   "First": "15%",
   "Second": "11%",
   "Third": "7%"
 },
 {
   "ID": 15,
   "Name": "Hurricane",
   "Power": 366,
   "MP": 85,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "AIR",
   "Effect": "CONFUSE",
   "Accuracy": 73,
   "Effect Chance": 13,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 8,
   "First": "12%",
   "Second": "8%",
   "Third": "0%"
 },
 {
   "ID": 16,
   "Name": "Giga Freeze",
   "Power": 264,
   "MP": 40,
   "Invincible Time": 5,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "STUN",
   "Accuracy": 65,
   "Effect Chance": 10,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": -100,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 6,
   "First": "17%",
   "Second": "10%",
   "Third": "5%"
 },
 {
   "ID": 17,
   "Name": "Ice Statue",
   "Power": 424,
   "MP": 62,
   "Invincible Time": 17,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "STUN",
   "Accuracy": 79,
   "Effect Chance": 38,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 122,
   "AI Target Distance": 7,
   "Unused": 0,
   "Tier": 7,
   "First": "15%",
   "Second": "8%",
   "Third": "0%"
 },
 {
   "ID": 18,
   "Name": "Winter Blast",
   "Power": 120,
   "MP": 55,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "ICE",
   "Effect": "STUN",
   "Accuracy": 90,
   "Effect Chance": 15,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 5,
   "First": "20%",
   "Second": "12%",
   "Third": "7%"
 },
 {
   "ID": 19,
   "Name": "Ice Needle",
   "Power": 126,
   "MP": 26,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "STUN",
   "Accuracy": 50,
   "Effect Chance": 5,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 2,
   "First": "30%",
   "Second": "15%",
   "Third": "8%"
 },
 {
   "ID": 20,
   "Name": "Water Blit",
   "Power": 211,
   "MP": 34,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 74,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 3,
   "First": "20%",
   "Second": "10%",
   "Third": "5%"
 },
 {
   "ID": 21,
   "Name": "Aqua Magic",
   "Power": 0,
   "MP": 12,
   "Invincible Time": 1,
   "Range": "SELF",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 4,
   "First": "22%",
   "Second": "14%",
   "Third": "9%"
 },
 {
   "ID": 22,
   "Name": "Aurora Freeze",
   "Power": 430,
   "MP": 86,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "ICE",
   "Effect": "FLAT",
   "Accuracy": 81,
   "Effect Chance": 24,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 8,
   "First": "14%",
   "Second": "6%",
   "Third": "0%"
 },
 {
   "ID": 23,
   "Name": "Tear Drop",
   "Power": 60,
   "MP": 14,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "FLAT",
   "Accuracy": 44,
   "Effect Chance": 46,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 1,
   "First": "30%",
   "Second": "22%",
   "Third": "15%"
 },
 {
   "ID": 24,
   "Name": "Power Crane",
   "Power": 226,
   "MP": 42,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 53,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 122,
   "AI Target Distance": 7,
   "Unused": 0,
   "Tier": 1,
   "First": "40%",
   "Second": "30%",
   "Third": "22%"
 },
 {
   "ID": 25,
   "Name": "All Range Beam",
   "Power": 573,
   "MP": 110,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 81,
   "Effect Chance": 0,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 7,
   "First": "16%",
   "Second": "13%",
   "Third": "0%"
 },
 {
   "ID": 26,
   "Name": "Metal Sprinter",
   "Power": 150,
   "MP": 55,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 78,
   "Effect Chance": 0,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": -48,
   "AI Target Distance": 3,
   "Unused": 0,
   "Tier": 2,
   "First": "35%",
   "Second": "27%",
   "Third": "18%"
 },
 {
   "ID": 27,
   "Name": "Pulse Laser",
   "Power": 389,
   "MP": 56,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 72,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 4,
   "First": "28%",
   "Second": "21%",
   "Third": "13%"
 },
 {
   "ID": 28,
   "Name": "Delete Program",
   "Power": 430,
   "MP": 73,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "FLAT",
   "Accuracy": 65,
   "Effect Chance": 50,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 6,
   "First": "20%",
   "Second": "14%",
   "Third": "10%"
 },
 {
   "ID": 29,
   "Name": "DG Dimension",
   "Power": 722,
   "MP": 140,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 8,
   "First": "15%",
   "Second": "12%",
   "Third": "0%"
 },
 {
   "ID": 30,
   "Name": "Full Potential",
   "Power": 0,
   "MP": 33,
   "Invincible Time": 1,
   "Range": "SELF",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 5,
   "First": "25%",
   "Second": "17%",
   "Third": "11%"
 },
 {
   "ID": 31,
   "Name": "Reverse Prog",
   "Power": 256,
   "MP": 99,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "FLAT",
   "Accuracy": 100,
   "Effect Chance": 12,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 122,
   "AI Target Distance": 7,
   "Unused": 0,
   "Tier": 3,
   "First": "32%",
   "Second": "24%",
   "Third": "15%"
 },
 {
   "ID": 32,
   "Name": "Poison Powder",
   "Power": 117,
   "MP": 57,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "EARTH",
   "Effect": "POISON",
   "Accuracy": 77,
   "Effect Chance": 62,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 3,
   "First": "26%",
   "Second": "19%",
   "Third": "14%"
 },
 {
   "ID": 33,
   "Name": "Bug",
   "Power": 500,
   "MP": 118,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "EARTH",
   "Effect": "FLAT",
   "Accuracy": 80,
   "Effect Chance": 35,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 8,
   "First": "12%",
   "Second": "8%",
   "Third": "0%"
 },
 {
   "ID": 34,
   "Name": "Mass Morph",
   "Power": 0,
   "MP": 10,
   "Invincible Time": 1,
   "Range": "SELF",
   "Type": "EARTH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 5,
   "First": "23%",
   "Second": "15%",
   "Third": "12%"
 },
 {
   "ID": 35,
   "Name": "Insect Plague",
   "Power": 58,
   "MP": 32,
   "Invincible Time": 12,
   "Range": "LARGE",
   "Type": "EARTH",
   "Effect": "POISON",
   "Accuracy": 83,
   "Effect Chance": 90,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 4,
   "First": "24%",
   "Second": "16%",
   "Third": "13%"
 },
 {
   "ID": 36,
   "Name": "Charm Perfume",
   "Power": 180,
   "MP": 70,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "EARTH",
   "Effect": "CONFUSE",
   "Accuracy": 75,
   "Effect Chance": 57,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 6,
   "First": "18%",
   "Second": "12%",
   "Third": "9%"
 },
 {
   "ID": 37,
   "Name": "Poison Claw",
   "Power": 62,
   "MP": 17,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "EARTH",
   "Effect": "POISON",
   "Accuracy": 60,
   "Effect Chance": 40,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 1,
   "First": "28%",
   "Second": "22%",
   "Third": "16%"
 },
 {
   "ID": 38,
   "Name": "Danger Sting",
   "Power": 157,
   "MP": 34,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "EARTH",
   "Effect": "FLAT",
   "Accuracy": 70,
   "Effect Chance": 26,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 2,
   "First": "27%",
   "Second": "20%",
   "Third": "15%"
 },
 {
   "ID": 39,
   "Name": "Green Trap",
   "Power": 310,
   "MP": 49,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "EARTH",
   "Effect": "STUN",
   "Accuracy": 82,
   "Effect Chance": 55,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": 7,
   "First": "14%",
   "Second": "10%",
   "Third": "0%"
 },
 {
   "ID": 40,
   "Name": "Tremar",
   "Power": 178,
   "MP": 56,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 60,
   "Effect Chance": 0,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 7,
   "First": "18%",
   "Second": "8%",
   "Third": "0%"
 },
 {
   "ID": 41,
   "Name": "Muscle Charge",
   "Power": 0,
   "MP": 22,
   "Invincible Time": 1,
   "Range": "SELF",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 6,
   "First": "19%",
   "Second": "9%",
   "Third": "8%"
 },
 {
   "ID": 42,
   "Name": "War Cry",
   "Power": 0,
   "MP": 14,
   "Invincible Time": 1,
   "Range": "SELF",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 3,
   "First": "22%",
   "Second": "15%",
   "Third": "10%"
 },
 {
   "ID": 43,
   "Name": "Sonic Jab",
   "Power": 52,
   "MP": 6,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 53,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 1,
   "First": "26%",
   "Second": "19%",
   "Third": "14%"
 },
 {
   "ID": 44,
   "Name": "Dynamite Kick",
   "Power": 193,
   "MP": 33,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "BATTLE",
   "Effect": "STUN",
   "Accuracy": 62,
   "Effect Chance": 3,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 2,
   "First": "24%",
   "Second": "17%",
   "Third": "12%"
 },
 {
   "ID": 45,
   "Name": "Counter",
   "Power": 285,
   "MP": 55,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "BATTLE",
   "Effect": "CONFUSE",
   "Accuracy": 100,
   "Effect Chance": 10,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 5,
   "First": "20%",
   "Second": "11%",
   "Third": "8%"
 },
 {
   "ID": 46,
   "Name": "Megaton Punch",
   "Power": 320,
   "MP": 62,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "BATTLE",
   "Effect": "STUN",
   "Accuracy": 70,
   "Effect Chance": 9,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 4,
   "First": "21%",
   "Second": "13%",
   "Third": "9%"
 },
 {
   "ID": 47,
   "Name": "Buster Dive",
   "Power": 500,
   "MP": 86,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "BATTLE",
   "Effect": "CONFUSE",
   "Accuracy": 80,
   "Effect Chance": 14,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 8,
   "First": "16%",
   "Second": "7%",
   "Third": "0%"
 },
 {
   "ID": 48,
   "Name": "Dynamite Kick",
   "Power": 255,
   "MP": 33,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 90,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "24%",
   "Second": "17%",
   "Third": "12%"
 },
 {
   "ID": 49,
   "Name": "Odor Spray",
   "Power": 88,
   "MP": 25,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FILTH",
   "Effect": "STUN",
   "Accuracy": 37,
   "Effect Chance": 10,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 39,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 2,
   "First": "24%",
   "Second": "14%",
   "Third": "9%"
 },
 {
   "ID": 50,
   "Name": "Poop Spd Toss",
   "Power": 122,
   "MP": 32,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FILTH",
   "Effect": "POISON",
   "Accuracy": 40,
   "Effect Chance": 11,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 122,
   "AI Target Distance": 7,
   "Unused": 0,
   "Tier": 3,
   "First": "23%",
   "Second": "13%",
   "Third": "8%"
 },
 {
   "ID": 51,
   "Name": "Big Poop Toss",
   "Power": 211,
   "MP": 64,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FILTH",
   "Effect": "CONFUSE",
   "Accuracy": 49,
   "Effect Chance": 17,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 6,
   "First": "15%",
   "Second": "10%",
   "Third": "5%"
 },
 {
   "ID": 52,
   "Name": "Big Rnd Toss",
   "Power": 211,
   "MP": 94,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "FILTH",
   "Effect": "CONFUSE",
   "Accuracy": 47,
   "Effect Chance": 20,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 7,
   "First": "11%",
   "Second": "8%",
   "Third": "0%"
 },
 {
   "ID": 53,
   "Name": "Poop Rnd Toss",
   "Power": 75,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "FILTH",
   "Effect": "POISON",
   "Accuracy": 33,
   "Effect Chance": 9,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": 4,
   "First": "21%",
   "Second": "12%",
   "Third": "7%"
 },
 {
   "ID": 54,
   "Name": "Rnd Spd Toss",
   "Power": 122,
   "MP": 72,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "FILTH",
   "Effect": "POISON",
   "Accuracy": 50,
   "Effect Chance": 10,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": -48,
   "AI Target Distance": 3,
   "Unused": 0,
   "Tier": 5,
   "First": "20%",
   "Second": "11%",
   "Third": "6%"
 },
 {
   "ID": 55,
   "Name": "Horizontal Kick",
   "Power": 53,
   "MP": 8,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "FILTH",
   "Effect": "NONE",
   "Accuracy": 41,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": 1,
   "First": "25%",
   "Second": "16%",
   "Third": "10%"
 },
 {
   "ID": 56,
   "Name": "Ult Poop Hell",
   "Power": 333,
   "MP": 111,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "FILTH",
   "Effect": "FLAT",
   "Accuracy": 100,
   "Effect Chance": 83,
   "Unknown1": 2,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": 8,
   "First": "9%",
   "Second": "7%",
   "Third": "0%"
 },
 {
   "ID": 57,
   "Name": "Horizontal Kick",
   "Power": 53,
   "MP": 8,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "FILTH",
   "Effect": "NONE",
   "Accuracy": 41,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "25%",
   "Second": "16%",
   "Third": "10%"
 },
 {
   "ID": 58,
   "Name": "Blaze Blast",
   "Power": 174,
   "MP": 40,
   "Invincible Time": 15,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "0%",
   "Second": "0%",
   "Third": "108%"
 },
 {
   "ID": 59,
   "Name": "Pepper Breath",
   "Power": 89,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "76%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 60,
   "Name": "Lovely Attack",
   "Power": 230,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "120%",
   "Second": "76%",
   "Third": "18%"
 },
 {
   "ID": 61,
   "Name": "Fireball",
   "Power": 155,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-120%",
   "Third": "76%"
 },
 {
   "ID": 62,
   "Name": "Death Claw",
   "Power": 180,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "-108%"
 },
 {
   "ID": 63,
   "Name": "Mega Flame",
   "Power": 196,
   "MP": 40,
   "Invincible Time": 15,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "76%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 64,
   "Name": "Howling Blaster",
   "Power": 183,
   "MP": 40,
   "Invincible Time": 15,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "-96%",
   "Second": "76%",
   "Third": "18%"
 },
 {
   "ID": 65,
   "Name": "Party time",
   "Power": 100,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FILTH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 66,
   "AI Target Distance": 15,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-84%",
   "Third": "76%"
 },
 {
   "ID": 66,
   "Name": "Electric Shock",
   "Power": 92,
   "MP": 40,
   "Invincible Time": 20,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 39,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "-72%"
 },
 {
   "ID": 67,
   "Name": "Abduction Beam",
   "Power": 222,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "76%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 68,
   "Name": "Smiley Bomb",
   "Power": 225,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-56%",
   "Second": "76%",
   "Third": "18%"
 },
 {
   "ID": 69,
   "Name": "Spnning Needle",
   "Power": 152,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-44%",
   "Third": "76%"
 },
 {
   "ID": 70,
   "Name": "Spiral Twister",
   "Power": 91,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "-28%"
 },
 {
   "ID": 71,
   "Name": "Boom Bubble",
   "Power": 85,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "76%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 72,
   "Name": "Sweet Breath",
   "Power": 130,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "EARTH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-12%",
   "Second": "76%",
   "Third": "18%"
 },
 {
   "ID": 73,
   "Name": "Bit Bomb",
   "Power": 232,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "EARTH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 122,
   "AI Target Distance": 7,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "4%",
   "Third": "77%"
 },
 {
   "ID": 74,
   "Name": "Deadly Bomb",
   "Power": 260,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "20%"
 },
 {
   "ID": 75,
   "Name": "Drill Spin",
   "Power": 150,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "77%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 76,
   "Name": "Electric Thread",
   "Power": 94,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": -100,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "36%",
   "Second": "77%",
   "Third": "18%"
 },
 {
   "ID": 77,
   "Name": "Energy Bomb",
   "Power": 214,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "48%",
   "Third": "77%"
 },
 {
   "ID": 78,
   "Name": "Genoside Attack",
   "Power": 215,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "64%"
 },
 {
   "ID": 79,
   "Name": "Giga Scissor Claw",
   "Power": 215,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": null,
   "First": "77%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 80,
   "Name": "Dark Shot",
   "Power": 200,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": null,
   "First": "76%",
   "Second": "77%",
   "Third": "18%"
 },
 {
   "ID": 81,
   "Name": "Pummel Whack",
   "Power": 170,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "88%",
   "Third": "77%"
 },
 {
   "ID": 82,
   "Name": "Hand of Fate",
   "Power": 166,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "100%"
 },
 {
   "ID": 83,
   "Name": "Dark Claw",
   "Power": 143,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "77%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 84,
   "Name": "Aerial Attack",
   "Power": 153,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "116%",
   "Second": "77%",
   "Third": "18%"
 },
 {
   "ID": 85,
   "Name": "Bone Boomerang",
   "Power": 148,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-128%",
   "Third": "77%"
 },
 {
   "ID": 86,
   "Name": "Solar Ray",
   "Power": 167,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "-116%"
 },
 {
   "ID": 87,
   "Name": "Hydro Pressure",
   "Power": 155,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": null,
   "First": "77%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 88,
   "Name": "Ice Blast",
   "Power": 162,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 122,
   "AI Target Distance": 7,
   "Unused": 0,
   "Tier": null,
   "First": "-104%",
   "Second": "77%",
   "Third": "18%"
 },
 {
   "ID": 89,
   "Name": "Iga School Knife Throw",
   "Power": 150,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-88%",
   "Third": "77%"
 },
 {
   "ID": 90,
   "Name": "Blasting Spout",
   "Power": 150,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "-76%"
 },
 {
   "ID": 91,
   "Name": "Fist of the Beast King",
   "Power": 170,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "77%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 92,
   "Name": "Dark Network & Concert Crush",
   "Power": 202,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "WIDE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "-64%",
   "Second": "77%",
   "Third": "18%"
 },
 {
   "ID": 93,
   "Name": "Electro Shocker",
   "Power": 170,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-48%",
   "Third": "77%"
 },
 {
   "ID": 94,
   "Name": "Meteor Wing",
   "Power": 158,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "-32%"
 },
 {
   "ID": 95,
   "Name": "Super Slap",
   "Power": 91,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 39,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "77%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 96,
   "Name": "Nightmare Syndromer",
   "Power": 222,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-20%",
   "Second": "77%",
   "Third": "18%"
 },
 {
   "ID": 97,
   "Name": "Frozen Fire Shot",
   "Power": 159,
   "MP": 40,
   "Invincible Time": 20,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-4%",
   "Third": "77%"
 },
 {
   "ID": 98,
   "Name": "Poison Ivy",
   "Power": 101,
   "MP": 40,
   "Invincible Time": 4,
   "Range": "SHORT",
   "Type": "EARTH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "12%"
 },
 {
   "ID": 99,
   "Name": "Blue Blaster",
   "Power": 90,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "78%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 100,
   "Name": "Scissor Claw",
   "Power": 172,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "BATTLE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "28%",
   "Second": "78%",
   "Third": "18%"
 },
 {
   "ID": 101,
   "Name": "Super Thunder Strike",
   "Power": 100,
   "MP": 40,
   "Invincible Time": 20,
   "Range": "LARGE",
   "Type": "AIR",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 16,
   "Unknown5": 39,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "44%",
   "Third": "78%"
 },
 {
   "ID": 102,
   "Name": "Spiral Sword",
   "Power": 210,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": -112,
   "Unknown5": 95,
   "AI Target Distance": 1,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "56%"
 },
 {
   "ID": 103,
   "Name": "Variable Darts",
   "Power": 153,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "67%",
   "Second": "19%",
   "Third": "-128%"
 },
 {
   "ID": 104,
   "Name": "Volcanic Strike",
   "Power": 160,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "60%",
   "Second": "78%",
   "Third": "18%"
 },
 {
   "ID": 105,
   "Name": "Subzero Ice Punch",
   "Power": 157,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "SHORT",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "72%",
   "Third": "78%"
 },
 {
   "ID": 106,
   "Name": "Infinity Cannon",
   "Power": 777,
   "MP": 40,
   "Invincible Time": 38,
   "Range": "LARGE",
   "Type": "MECH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 66,
   "AI Target Distance": 15,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "88%"
 },
 {
   "ID": 107,
   "Name": "Party time",
   "Power": 100,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FILTH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 66,
   "AI Target Distance": 15,
   "Unused": 0,
   "Tier": null,
   "First": "78%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 108,
   "Name": "Party time",
   "Power": 100,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FILTH",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 66,
   "AI Target Distance": 15,
   "Unused": 0,
   "Tier": null,
   "First": "104%",
   "Second": "78%",
   "Third": "18%"
 },
 {
   "ID": 109,
   "Name": "Crimson Flare",
   "Power": 213,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "116%",
   "Third": "78%"
 },
 {
   "ID": 110,
   "Name": "Glacial Blast",
   "Power": 0,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "NONE",
   "Type": "NONE",
   "Effect": "NONE",
   "Accuracy": 0,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 0,
   "AI Target Distance": 0,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "-124%"
 },
 {
   "ID": 111,
   "Name": "Mail Strome",
   "Power": 211,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "78%",
   "Second": "18%",
   "Third": "-128%"
 },
 {
   "ID": 112,
   "Name": "High Electro Shocker",
   "Power": 218,
   "MP": 40,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "FIRE",
   "Effect": "NONE",
   "Accuracy": 100,
   "Effect Chance": 0,
   "Unknown1": 1,
   "Unused": 0,
   "Unknown4": 64,
   "Unknown5": 126,
   "AI Target Distance": 5,
   "Unused": 0,
   "Tier": null,
   "First": "60%",
   "Second": "67%",
   "Third": "19%"
 },
 {
   "ID": 113,
   "Name": "Bubble",
   "Power": 6,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-112%",
   "Third": "78%"
 },
 {
   "ID": 114,
   "Name": "Bubble",
   "Power": 6,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "68%"
 },
 {
   "ID": 115,
   "Name": "Bubble",
   "Power": 5,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "67%",
   "Second": "19%",
   "Third": "-128%"
 },
 {
   "ID": 116,
   "Name": "Bubble",
   "Power": 5,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "-96%",
   "Second": "78%",
   "Third": "18%"
 },
 {
   "ID": 117,
   "Name": "Bubble",
   "Power": 10,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "-128%",
   "Second": "-84%",
   "Third": "78%"
 },
 {
   "ID": 118,
   "Name": "Bubble",
   "Power": 11,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "18%",
   "Second": "-128%",
   "Third": "76%"
 },
 {
   "ID": 119,
   "Name": "Bubble",
   "Power": 10,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "67%",
   "Second": "19%",
   "Third": "-128%"
 },
 {
   "ID": 120,
   "Name": "Bubble",
   "Power": 10,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 2,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": 113,
   "AI Target Distance": 2,
   "Unused": 0,
   "Tier": null,
   "First": "-68%",
   "Second": "78%",
   "Third": "18%"
 },
 {
   "ID": 121,
   "Name": "△z",
   "Power": 10,
   "MP": 0,
   "Invincible Time": 1,
   "Range": "LARGE",
   "Type": "ICE",
   "Effect": "NONE",
   "Accuracy": 70,
   "Effect Chance": 0,
   "Unknown1": 0,
   "Unused": 0,
   "Unknown4": 0,
   "Unknown5": -60,
   "AI Target Distance": 9,
   "Unused": 0,
   "Tier": null,
   "First": "n/a",
   "Second": "n/a",
   "Third": "n/a"
 }
];