const food=[
 {
   "ID": 38,
   "Item": "Meat",
   "Energy": 12,
   "Weight": 1,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 39,
   "Item": "Giant Meat",
   "Energy": 24,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 40,
   "Item": "Sirloin",
   "Energy": 35,
   "Weight": 3,
   "Tiredness": -5,
   "Happiness": 3,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 41,
   "Item": "Super Carrot",
   "Energy": 10,
   "Weight": -2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": "MP+OFF+BRN",
   "Buff Value": 12,
   "Buff Duration": 6
 },
 {
   "ID": 42,
   "Item": "Hawk Raddish",
   "Energy": 15,
   "Weight": 3,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": "HP+DEF+SPD",
   "Buff Value": 12,
   "Buff Duration": 6
 },
 {
   "ID": 43,
   "Item": "Spiny Green",
   "Energy": 9,
   "Weight": 1,
   "Tiredness": -50,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 44,
   "Item": "Digimushroom",
   "Energy": 12,
   "Weight": 1,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 45,
   "Item": "Icemushroom",
   "Energy": 19,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": 50,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 46,
   "Item": "Deluxemushroom",
   "Energy": 38,
   "Weight": 4,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": 100,
   "MP": 100,
   "Offense": 10,
   "Defense": 10,
   "Speed": 10,
   "Brains": 10,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 47,
   "Item": "Digipine",
   "Energy": 22,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": "ALL",
   "Buff Value": 15,
   "Buff Duration": 6
 },
 {
   "ID": 48,
   "Item": "Blue Apple",
   "Energy": 30,
   "Weight": 3,
   "Tiredness": null,
   "Happiness": 50,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 49,
   "Item": "Red Berry",
   "Energy": 25,
   "Weight": 2,
   "Tiredness": -20,
   "Happiness": 20,
   "Discipline": 20,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 50,
   "Item": "Gold Acorn",
   "Energy": 40,
   "Weight": 4,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 51,
   "Item": "Big Berry",
   "Energy": 100,
   "Weight": 4,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 52,
   "Item": "Sweet Nut",
   "Energy": 20,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": 9999,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 53,
   "Item": "Super Veggy",
   "Energy": 16,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": 9999,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 54,
   "Item": "Prickly Pear",
   "Energy": 33,
   "Weight": -5,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 55,
   "Item": "Orange Banana",
   "Energy": 24,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": 1000,
   "Heal MP": 1000,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 56,
   "Item": "Powerfruit",
   "Energy": 20,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": 20,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 57,
   "Item": "Power Ice",
   "Energy": 20,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": 20,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 58,
   "Item": "Speed Leaf",
   "Energy": 20,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": 20,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 59,
   "Item": "Sage Fruit",
   "Energy": 20,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": 20,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 60,
   "Item": "Muscle Yam",
   "Energy": 20,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": 200,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 61,
   "Item": "Calm Berry",
   "Energy": 20,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": 200,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 62,
   "Item": "Digianchovy",
   "Energy": 8,
   "Weight": 1,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 63,
   "Item": "Digisnapper",
   "Energy": 12,
   "Weight": 1,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 64,
   "Item": "DigiTrout",
   "Energy": 22,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 65,
   "Item": "Black Trout",
   "Energy": 27,
   "Weight": -2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": 10,
   "MP": 10,
   "Offense": 1,
   "Defense": 1,
   "Speed": 1,
   "Brains": 1,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 66,
   "Item": "Digicatfish",
   "Energy": 49,
   "Weight": 5,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 67,
   "Item": "Digiseabass",
   "Energy": 35,
   "Weight": 4,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": 3,
   "Sickness": "20%",
   "Heal HP": 9999,
   "Heal MP": 9999,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 68,
   "Item": "Moldy Meat",
   "Energy": 30,
   "Weight": 2,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": "100%",
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 69,
   "Item": "Happymushroom",
   "Energy": 15,
   "Weight": 1,
   "Tiredness": -30,
   "Happiness": 30,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": "30%",
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 70,
   "Item": "Chain Melon",
   "Energy": 50,
   "Weight": 3,
   "Tiredness": -50,
   "Happiness": 50,
   "Discipline": null,
   "Lifetime": 20,
   "Sickness": "5%",
   "Heal HP": null,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 121,
   "Item": "Rain Plant",
   "Energy": null,
   "Weight": null,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": null,
   "Heal HP": null,
   "Heal MP": 1000,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 },
 {
   "ID": 122,
   "Item": "Steak",
   "Energy": 32,
   "Weight": null,
   "Tiredness": null,
   "Happiness": null,
   "Discipline": null,
   "Lifetime": null,
   "Sickness": "20%",
   "Heal HP": 1000,
   "Heal MP": null,
   "HP": null,
   "MP": null,
   "Offense": null,
   "Defense": null,
   "Speed": null,
   "Brains": null,
   "Buff Flag": null,
   "Buff Value": null,
   "Buff Duration": null
 }
];
let foods=[];
for(let f in food){
   o={};
o.id=food[f].ID;
o.item=food[f].Item;
//o.=food[f].;

if(food[f].Energy!==null){
   o.energy=food[f].Energy;
}
if(food[f].Weight!==null){
   o.weight=food[f].Weight;
}
if(food[f].Tiredness!==null){
   o.tiredness=food[f].Tiredness;
}
if(food[f].Happiness!==null){
   o.happines=food[f].Happiness;
}
if(food[f].Discipline!==null){
   o.discipline=food[f].Discipline;
}
if(food[f].Lifetime!==null){
   o.lifetime=food[f].Lifetime;
}
if(food[f].Sickness!==null){
   o.sickness=food[f].Sickness;
}
if(food[f]["Heal HP"]!==null){
   o.healHP=food[f]["Heal HP"];
}
if(food[f]["Heal MP"]!==null){
   o.healMP=food[f]["Heal MP"];
}
if(food[f].HP!==null){
   o.hp=food[f].HP;
}
if(food[f].MP!==null){
   o.mp=food[f].MP;
}
if(food[f].Offense!==null){
   o.offense=food[f].Offense;
}
if(food[f].Defense!==null){
   o.defense=food[f].Defense;
}
if(food[f].Speed!==null){
   o.speed=food[f].Speed;
}
if(food[f].Brains!==null){
   o.brains=food[f].Brains;
}
if(food[f]["Buff Flag"]!==null){
   o.buff=food[f]["Buff Flag"]+" x"+parseInt(food[f]["Buff Value"])/10;  
}
foods.push(o);
}
alert(JSON.stringify(foods));