/*[
  {
    "Name": "Hiro",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 0,
    "E.Threshold": 0,
    "E.Usage": 0,
    "Unknown1": 0,
    "Poop Timer": 0,
    "Unknown2": 0,
    "Unknown3": 0,
    "Unknown4": 0,
    "PoopSize": 0,
    "FavoriteFood": "-",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 0,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 0,
    "ViewX": 670,
    "ViewY": 200,
    "ViewZ": -2270
  },
  */
var digiRaise=[];
digiRaise.push({
    "Name": "Botamon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 6,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 6,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_1",
    "PreferedMapType": 8,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 5,
    "ViewX": 710,
    "ViewY": 140,
    "ViewZ": -2210
});
digiRaise.push({
    "Name": "Koromon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 10,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 7,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_2",
    "PreferedMapType": 8,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 10,
    "ViewX": 460,
    "ViewY": 210,
    "ViewZ": -1770
});
digiRaise.push({
    "Name": "Agumon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 20,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": 0,
    "Unknown4": 0,
    "PoopSize": 8,
    "FavoriteFood": "Meat",
    "SleepCycle": "DAY",
    "PreferedMapType": 0,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 15,
    "ViewX": 550,
    "ViewY": 230,
    "ViewZ": -1870
});
digiRaise.push({
    "Name": "Betamon",
    "Hunger#1": 0,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 14,
    "Hunger#5": 19,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 22,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Digisnapper",
    "SleepCycle": "GROGGY",
    "PreferedMapType": 4,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 15,
    "ViewX": 370,
    "ViewY": 230,
    "ViewZ": -1570
});
digiRaise.push({
    "Name": "Greymon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 45,
    "E.Usage": 9,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 12,
    "FavoriteFood": "Sirloin",
    "SleepCycle": "DAY",
    "PreferedMapType": 0,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 30,
    "ViewX": 30,
    "ViewY": 390,
    "ViewZ": -880
});
digiRaise.push({
    "Name": "Devimon",
    "Hunger#1": 4,
    "Hunger#2": 9,
    "Hunger#3": 14,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 30,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Deluxmushrm",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 6,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 20,
    "ViewX": 130,
    "ViewY": 350,
    "ViewZ": -1120
});
digiRaise.push({
    "Name": "Airdramon",
    "Hunger#1": 5,
    "Hunger#2": 11,
    "Hunger#3": 17,
    "Hunger#4": 23,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Sirloin",
    "SleepCycle": "DAY",
    "PreferedMapType": 2,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 30,
    "ViewX": 260,
    "ViewY": 380,
    "ViewZ": -1450
});
digiRaise.push({
    "Name": "Tyrannomon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 55,
    "E.Usage": 14,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 13,
    "FavoriteFood": "Big Berry",
    "SleepCycle": "SLEEPY",
    "PreferedMapType": 0,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 30,
    "ViewX": 50,
    "ViewY": 340,
    "ViewZ": -940
});
digiRaise.push({
    "Name": "Meramon",
    "Hunger#1": 4,
    "Hunger#2": 9,
    "Hunger#3": 14,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Supercarrot",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 0,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 20,
    "ViewX": 130,
    "ViewY": 360,
    "ViewZ": -1090
});
digiRaise.push({
    "Name": "Seadramon",
    "Hunger#1": 0,
    "Hunger#2": 4,
    "Hunger#3": 8,
    "Hunger#4": 12,
    "Hunger#5": 16,
    "Hunger#6": 20,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 42,
    "E.Usage": 11,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 11,
    "FavoriteFood": "Black trout",
    "SleepCycle": "GROGGY",
    "PreferedMapType": 4,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 30,
    "ViewX": 230,
    "ViewY": 280,
    "ViewZ": -1400
});
digiRaise.push({
    "Name": "Numemon",
    "Hunger#1": 0,
    "Hunger#2": 3,
    "Hunger#3": 6,
    "Hunger#4": 9,
    "Hunger#5": 12,
    "Hunger#6": 15,
    "Hunger#7": 18,
    "Hunger#8": 21,
    "E.Capacity": 80,
    "E.Threshold": 34,
    "E.Usage": 11,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 13,
    "FavoriteFood": "Moldy Meat",
    "SleepCycle": "GROGGY",
    "PreferedMapType": 6,
    "TrainingType": "FILTH",
    "DefaultWeight": 20,
    "ViewX": 270,
    "ViewY": 280,
    "ViewZ": -1340
});
digiRaise.push({
    "Name": "MetalGreymon",
    "Hunger#1": 0,
    "Hunger#2": 4,
    "Hunger#3": 8,
    "Hunger#4": 12,
    "Hunger#5": 16,
    "Hunger#6": 20,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 45,
    "E.Usage": 11,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 15,
    "FavoriteFood": "Super veggy",
    "SleepCycle": "GROGGY",
    "PreferedMapType": 3,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 50,
    "ViewX": -30,
    "ViewY": 390,
    "ViewZ": -780
});
digiRaise.push({
    "Name": "Mamemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 24,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Sweet Nut",
    "SleepCycle": "DAY",
    "PreferedMapType": 3,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 5,
    "ViewX": 570,
    "ViewY": 170,
    "ViewZ": -1900
});
digiRaise.push({
    "Name": "Monzaemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 40,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Digipine",
    "SleepCycle": "DAY",
    "PreferedMapType": 2,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 40,
    "ViewX": 340,
    "ViewY": 300,
    "ViewZ": -1460
});
digiRaise.push({
    "Name": "Punimon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 6,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 6,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_1",
    "PreferedMapType": 8,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 5,
    "ViewX": 660,
    "ViewY": 160,
    "ViewZ": -2090
});
digiRaise.push({
    "Name": "Tsunomon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 10,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 7,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_2",
    "PreferedMapType": 8,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 10,
    "ViewX": 460,
    "ViewY": 220,
    "ViewZ": -1720
});
digiRaise.push({
    "Name": "Gabumon",
    "Hunger#1": 2,
    "Hunger#2": 5,
    "Hunger#3": 8,
    "Hunger#4": 11,
    "Hunger#5": 14,
    "Hunger#6": 17,
    "Hunger#7": 20,
    "Hunger#8": 23,
    "E.Capacity": 40,
    "E.Threshold": 25,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Meat",
    "SleepCycle": "GROGGY",
    "PreferedMapType": 5,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 15,
    "ViewX": 420,
    "ViewY": 230,
    "ViewZ": -1610
});
digiRaise.push({
    "Name": "Elecmon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 23,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Digianchovy",
    "SleepCycle": "DAY",
    "PreferedMapType": 5,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 15,
    "ViewX": 250,
    "ViewY": 240,
    "ViewZ": -1410
});
digiRaise.push({
    "Name": "Kabuterimon",
    "Hunger#1": 2,
    "Hunger#2": 7,
    "Hunger#3": 12,
    "Hunger#4": 17,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 45,
    "E.Usage": 9,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 12,
    "FavoriteFood": "Power Ice",
    "SleepCycle": "NIGHT",
    "PreferedMapType": 7,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 30,
    "ViewX": 210,
    "ViewY": 360,
    "ViewZ": -1290
});
digiRaise.push({
    "Name": "Angemon",
    "Hunger#1": 7,
    "Hunger#2": 12,
    "Hunger#3": 17,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 24,
    "E.Usage": 4,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 9,
    "FavoriteFood": "Sage Fruit",
    "SleepCycle": "DAY",
    "PreferedMapType": 2,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 20,
    "ViewX": 50,
    "ViewY": 350,
    "ViewZ": -1030
});
digiRaise.push({
    "Name": "Birdramon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Red Berry",
    "SleepCycle": "DAY",
    "PreferedMapType": 0,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 20,
    "ViewX": 250,
    "ViewY": 400,
    "ViewZ": -1320
});
digiRaise.push({
    "Name": "Garurumon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Giant Meat",
    "SleepCycle": "DAY",
    "PreferedMapType": 1,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 30,
    "ViewX": 190,
    "ViewY": 290,
    "ViewZ": -1200
});
digiRaise.push({
    "Name": "Frigimon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 42,
    "E.Usage": 11,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 11,
    "FavoriteFood": "Ice mushrm",
    "SleepCycle": "SLEEPY",
    "PreferedMapType": 1,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 30,
    "ViewX": 80,
    "ViewY": 340,
    "ViewZ": -1020
});
digiRaise.push({
    "Name": "Whamon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 50,
    "E.Usage": 13,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 15,
    "FavoriteFood": "Blue apple",
    "SleepCycle": "DAY",
    "PreferedMapType": 4,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 40,
    "ViewX": 200,
    "ViewY": 360,
    "ViewZ": -1360
});
digiRaise.push({
    "Name": "Vegiemon",
    "Hunger#1": 3,
    "Hunger#2": 7,
    "Hunger#3": 11,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 23,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 40,
    "E.Usage": 10,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 11,
    "FavoriteFood": "Hawk radish",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 5,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 10,
    "ViewX": 280,
    "ViewY": 270,
    "ViewZ": -1450
});
digiRaise.push({
    "Name": "SkullGreymon",
    "Hunger#1": 4,
    "Hunger#2": 12,
    "Hunger#3": 20,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 30,
    "E.Usage": 4,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 14,
    "FavoriteFood": "Digiseabass",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 6,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 30,
    "ViewX": 30,
    "ViewY": 390,
    "ViewZ": -940
});
digiRaise.push({
    "Name": "MetalMamemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 24,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Sweet Nut",
    "SleepCycle": "DAY",
    "PreferedMapType": 3,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 5,
    "ViewX": 550,
    "ViewY": 170,
    "ViewZ": -1900
});
digiRaise.push({
    "Name": "Vademon",
    "Hunger#1": 4,
    "Hunger#2": 9,
    "Hunger#3": 14,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 7,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Super veggy",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 3,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 15,
    "ViewX": 440,
    "ViewY": 350,
    "ViewZ": -1730
});
digiRaise.push({
    "Name": "Poyomon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 6,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 6,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_1",
    "PreferedMapType": 8,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 5,
    "ViewX": 680,
    "ViewY": 270,
    "ViewZ": -2140
});
digiRaise.push({
    "Name": "Tokomon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 10,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 7,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_2",
    "PreferedMapType": 8,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 10,
    "ViewX": 420,
    "ViewY": 220,
    "ViewZ": -1630
});
digiRaise.push({
    "Name": "Patamon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 20,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Digisnapper",
    "SleepCycle": "DAY",
    "PreferedMapType": 5,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 15,
    "ViewX": 470,
    "ViewY": 180,
    "ViewZ": -1720
});
digiRaise.push({
    "Name": "Kunemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 20,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Happymushrm",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 7,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 15,
    "ViewX": 290,
    "ViewY": 280,
    "ViewZ": -1380
});
digiRaise.push({
    "Name": "Unimon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 7,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 11,
    "FavoriteFood": "Giant Meat",
    "SleepCycle": "DAY",
    "PreferedMapType": 2,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 30,
    "ViewX": 240,
    "ViewY": 370,
    "ViewZ": -1360
});
digiRaise.push({
    "Name": "Ogremon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 48,
    "E.Usage": 12,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 13,
    "FavoriteFood": "Gold Acorn",
    "SleepCycle": "SLEEPY",
    "PreferedMapType": 5,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 30,
    "ViewX": 280,
    "ViewY": 340,
    "ViewZ": -1390
});
digiRaise.push({
    "Name": "Shellmon",
    "Hunger#1": 0,
    "Hunger#2": 4,
    "Hunger#3": 8,
    "Hunger#4": 12,
    "Hunger#5": 16,
    "Hunger#6": 20,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 56,
    "E.Usage": 14,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 15,
    "FavoriteFood": "Pricklypear",
    "SleepCycle": "GROGGY",
    "PreferedMapType": 4,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 40,
    "ViewX": 256,
    "ViewY": 320,
    "ViewZ": -880
});
digiRaise.push({
    "Name": "Centarumon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 40,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 11,
    "FavoriteFood": "Speed Leaf",
    "SleepCycle": "DAY",
    "PreferedMapType": 0,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 30,
    "ViewX": 310,
    "ViewY": 370,
    "ViewZ": -1370
});
digiRaise.push({
    "Name": "Bakemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 33,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 9,
    "FavoriteFood": "Happymushrm",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 6,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 20,
    "ViewX": 490,
    "ViewY": 340,
    "ViewZ": -1810
});
digiRaise.push({
    "Name": "Drimogemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 60,
    "E.Usage": 12,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 12,
    "FavoriteFood": "Giant Meat",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 5,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 40,
    "ViewX": 210,
    "ViewY": 340,
    "ViewZ": -1220
});
digiRaise.push({
    "Name": "Sukamon",
    "Hunger#1": 0,
    "Hunger#2": 3,
    "Hunger#3": 6,
    "Hunger#4": 9,
    "Hunger#5": 12,
    "Hunger#6": 15,
    "Hunger#7": 18,
    "Hunger#8": 21,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 11,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 13,
    "FavoriteFood": "Moldy Meat",
    "SleepCycle": "DAY",
    "PreferedMapType": 6,
    "TrainingType": "FILTH",
    "DefaultWeight": 30,
    "ViewX": 300,
    "ViewY": 260,
    "ViewZ": -1420
});
digiRaise.push({
    "Name": "Andromon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 32,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Deluxmushrm",
    "SleepCycle": "DAY",
    "PreferedMapType": 3,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 40,
    "ViewX": 260,
    "ViewY": 360,
    "ViewZ": -1400
});
digiRaise.push({
    "Name": "Giromon",
    "Hunger#1": 4,
    "Hunger#2": 9,
    "Hunger#3": 13,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 30,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Gold Acorn",
    "SleepCycle": "SLEEPY",
    "PreferedMapType": 3,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 5,
    "ViewX": 370,
    "ViewY": 270,
    "ViewZ": -1610
});
digiRaise.push({
    "Name": "Etemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 40,
    "E.Usage": 10,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Orange bana",
    "SleepCycle": "DAY",
    "PreferedMapType": 5,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 20,
    "ViewX": 500,
    "ViewY": 230,
    "ViewZ": -1870
});
digiRaise.push({
    "Name": "Yuramon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 6,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 6,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_1",
    "PreferedMapType": 8,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 5,
    "ViewX": 670,
    "ViewY": 230,
    "ViewZ": -2100
});
digiRaise.push({
    "Name": "Tanemon",
    "Hunger#1": -1,
    "Hunger#2": -1,
    "Hunger#3": -1,
    "Hunger#4": -1,
    "Hunger#5": -1,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 25,
    "E.Threshold": 10,
    "E.Usage": 3,
    "Unknown1": 0,
    "Poop Timer": 18,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 7,
    "FavoriteFood": "-",
    "SleepCycle": "BABY_2",
    "PreferedMapType": 8,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 10,
    "ViewX": 330,
    "ViewY": 230,
    "ViewZ": -1480
});
digiRaise.push({
    "Name": "Biyomon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 20,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Digimushrm",
    "SleepCycle": "DAY",
    "PreferedMapType": 5,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 15,
    "ViewX": 540,
    "ViewY": 210,
    "ViewZ": -1880
});
digiRaise.push({
    "Name": "Palmon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 23,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Digimushrm",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 5,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 15,
    "ViewX": 480,
    "ViewY": 260,
    "ViewZ": -1750
});
digiRaise.push({
    "Name": "Monochromon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 53,
    "E.Usage": 12,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 13,
    "FavoriteFood": "Digicatfish",
    "SleepCycle": "DAY",
    "PreferedMapType": 0,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 40,
    "ViewX": 256,
    "ViewY": 350,
    "ViewZ": -870
});
digiRaise.push({
    "Name": "Leomon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 33,
    "E.Usage": 7,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Sirloin",
    "SleepCycle": "DAY",
    "PreferedMapType": 5,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 20,
    "ViewX": 200,
    "ViewY": 330,
    "ViewZ": -1320
});
digiRaise.push({
    "Name": "Coelamon",
    "Hunger#1": 4,
    "Hunger#2": 8,
    "Hunger#3": 13,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 7,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "DigiTrout",
    "SleepCycle": "SLEEPY",
    "PreferedMapType": 4,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 30,
    "ViewX": 270,
    "ViewY": 380,
    "ViewZ": -1400
});
digiRaise.push({
    "Name": "Kokatorimon",
    "Hunger#1": 3,
    "Hunger#2": 8,
    "Hunger#3": 13,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 40,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 11,
    "FavoriteFood": "Black trout",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 5,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 30,
    "ViewX": 310,
    "ViewY": 330,
    "ViewZ": -1520
});
digiRaise.push({
    "Name": "Kuwagamon",
    "Hunger#1": 4,
    "Hunger#2": 9,
    "Hunger#3": 14,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 43,
    "E.Usage": 9,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 12,
    "FavoriteFood": "Power fruit",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 7,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 30,
    "ViewX": 60,
    "ViewY": 333,
    "ViewZ": -1030
});
digiRaise.push({
    "Name": "Mojyamon",
    "Hunger#1": 3,
    "Hunger#2": 8,
    "Hunger#3": 13,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 42,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 11,
    "FavoriteFood": "Digisnapper",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 1,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 20,
    "ViewX": 360,
    "ViewY": 270,
    "ViewZ": -1620
});
digiRaise.push({
    "Name": "Nanimon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 9,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Sirloin",
    "SleepCycle": "SLEEPY",
    "PreferedMapType": 6,
    "TrainingType": "FILTH",
    "DefaultWeight": 20,
    "ViewX": 530,
    "ViewY": 230,
    "ViewZ": -1890
});
digiRaise.push({
    "Name": "Megadramon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 45,
    "E.Usage": 11,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 14,
    "FavoriteFood": "Blue apple",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 3,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 50,
    "ViewX": 256,
    "ViewY": 460,
    "ViewZ": -940
});
digiRaise.push({
    "Name": "Piximon",
    "Hunger#1": 3,
    "Hunger#2": 8,
    "Hunger#3": 13,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 24,
    "E.Usage": 5,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Sweet Nut",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 2,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 5,
    "ViewX": 470,
    "ViewY": 330,
    "ViewZ": -1800
});
digiRaise.push({
    "Name": "Digitamamon",
    "Hunger#1": 0,
    "Hunger#2": 3,
    "Hunger#3": 6,
    "Hunger#4": 9,
    "Hunger#5": 12,
    "Hunger#6": 15,
    "Hunger#7": 18,
    "Hunger#8": 21,
    "E.Capacity": 80,
    "E.Threshold": 50,
    "E.Usage": 14,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 9,
    "FavoriteFood": "Chain melon",
    "SleepCycle": "DAY",
    "PreferedMapType": 6,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 10,
    "ViewX": 550,
    "ViewY": 200,
    "ViewZ": -1960
});
digiRaise.push({
    "Name": "Penguinmon",
    "Hunger#1": 1,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 13,
    "Hunger#5": 17,
    "Hunger#6": 21,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 40,
    "E.Threshold": 22,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 24,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Digianchovy",
    "SleepCycle": "DAY",
    "PreferedMapType": 1,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 15,
    "ViewX": 450,
    "ViewY": 240,
    "ViewZ": -1760
});
digiRaise.push({
    "Name": "Ninjamon",
    "Hunger#1": 3,
    "Hunger#2": 8,
    "Hunger#3": 13,
    "Hunger#4": 18,
    "Hunger#5": 23,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 24,
    "E.Usage": 6,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 8,
    "FavoriteFood": "Sweet Nut",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 5,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 10,
    "ViewX": 550,
    "ViewY": 180,
    "ViewZ": -1920
});
digiRaise.push({
    "Name": "Phoenixmon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 35,
    "E.Usage": 7,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 12,
    "FavoriteFood": "Calm berry",
    "SleepCycle": "DAY",
    "PreferedMapType": 0,
    "TrainingType": "MP_BRAINS",
    "DefaultWeight": 30,
    "ViewX": 120,
    "ViewY": 430,
    "ViewZ": -1230
});
digiRaise.push({
    "Name": "H-Kabuterimon",
    "Hunger#1": 2,
    "Hunger#2": 7,
    "Hunger#3": 12,
    "Hunger#4": 17,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 45,
    "E.Usage": 9,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 13,
    "FavoriteFood": "Muscle Yam",
    "SleepCycle": "NIGHT",
    "PreferedMapType": 7,
    "TrainingType": "HP_DEFENSE",
    "DefaultWeight": 40,
    "ViewX": 256,
    "ViewY": 360,
    "ViewZ": -950
});
digiRaise.push({
    "Name": "MegaSeadramon",
    "Hunger#1": 0,
    "Hunger#2": 5,
    "Hunger#3": 9,
    "Hunger#4": 14,
    "Hunger#5": 19,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 42,
    "E.Usage": 8,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 12,
    "FavoriteFood": "Digiseabass",
    "SleepCycle": "GROGGY",
    "PreferedMapType": 4,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 30,
    "ViewX": 110,
    "ViewY": 320,
    "ViewZ": -1180
});
/*
digiRaise.push({
    "Name": "WereGarurumon",
    "Hunger#1": 0,
    "Hunger#2": 0,
    "Hunger#3": 0,
    "Hunger#4": 0,
    "Hunger#5": 0,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 0,
    "E.Threshold": 0,
    "E.Usage": 0,
    "Unknown1": 0,
    "Poop Timer": 0,
    "Unknown2": 0,
    "Unknown3": 0,
    "Unknown4": 0,
    "PoopSize": 0,
    "FavoriteFood": "-",
    "SleepCycle": "SUNUP",
    "PreferedMapType": 0,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 0,
    "ViewX": 256,
    "ViewY": 256,
    "ViewZ": 0
});
digiRaise.push({
    "Name": "Panjyamon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 11,
    "Hunger#4": 16,
    "Hunger#5": 21,
    "Hunger#6": -1,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 33,
    "E.Usage": 7,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Sirloin",
    "SleepCycle": "DAY",
    "PreferedMapType": 2,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 20,
    "ViewX": 200,
    "ViewY": 330,
    "ViewZ": -1320
});
digiRaise.push({
    "Name": "Gigadramon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 45,
    "E.Usage": 11,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 14,
    "FavoriteFood": "Blue apple",
    "SleepCycle": "SUNSET",
    "PreferedMapType": 3,
    "TrainingType": "NEUTRAL",
    "DefaultWeight": 50,
    "ViewX": 256,
    "ViewY": 460,
    "ViewZ": -940
});
digiRaise.push({
    "Name": "MetalEtemon",
    "Hunger#1": 2,
    "Hunger#2": 6,
    "Hunger#3": 10,
    "Hunger#4": 14,
    "Hunger#5": 18,
    "Hunger#6": 22,
    "Hunger#7": -1,
    "Hunger#8": -1,
    "E.Capacity": 80,
    "E.Threshold": 40,
    "E.Usage": 10,
    "Unknown1": 0,
    "Poop Timer": 36,
    "Unknown2": 0,
    "Unknown3": -80,
    "Unknown4": 4,
    "PoopSize": 10,
    "FavoriteFood": "Orange bana",
    "SleepCycle": "DAY",
    "PreferedMapType": 3,
    "TrainingType": "OFFENSE_SPEED",
    "DefaultWeight": 20,
    "ViewX": 500,
    "ViewY": 230,
    "ViewZ": -1870
  });*/
var obj = null;
  for(var i=0;i<digiRaise.length;i++){
        obj=digimon.filter(function ( obj ) {
        return obj.name === digiRaise[i].Name;
        })[0];
        digiRaise[i].Level=obj.level;
  }
  console.log(digiRaise[0]);

  function byName(a, b) {
    var A = a.Name.toLowerCase();
    var B = b.Name.toLowerCase();
    if (A < B) {
        return -1;
    } else if (A > B) {
        return 1;
    } else {
        return 0;
    }
}
digiRaise.sort(byName);