var digimon=[
	{
		recruited:false,
		name:"Agumon",
		level:"Rookie",
		maps:[],
		recruitMap:"MAYO00",
		region:"Native Forest",
		trigger:"None",
		location:"Screen south of Green Gym",
		requirement:"He will challenge you to a fight - win it.",
		unlocks:"Item Bank",
		angemonTip:"",
		enemies:[
			{
				name:"Agumon",
				hp:400,
				mp:300,
				off:30,
				def:30,
				spd:30,
				brn:50,
				bits:100,
				item:"sm. recovery",
				dropChance:50,
				moves:[{name:"Spit Fire",chance:50},{name:"Sonic Jab",chance:50}],
				finisher:"Pepper Breath"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Kunemon",
		level:"Rookie",
		maps:[],
		recruitMap:"MAYO02",
		region:"Native Forest",
		trigger:"Have Food",
		location:"left screen from the Forest toilet",
		requirement:"He will ask you for food, once you give him something he will fight you - win the fight.",
		unlocks:"direct path from File City to Digimon bridge",
		angemonTip:"Insectoid Digimons like greenery. Like the kind around the city...",
		enemies:[
			{
				name:"Kunemon",
				hp:900,
				mp:2400,
				off:210,
				def:100,
				spd:120,
				brn:100,
				bits:1200,
				item:"MP Chip",
				dropChance:100,
				moves:[{name:"Static Elect",chance:44.44},{name:"Electric Cloud",chance:33.33},{name:"Danger Sting",chance:22.22}],
				finisher:"Electric Thread"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Palmon",
		level:"Rookie",
		maps:[],
		recruitMap:"MAYO03",
		region:"Native Forest",
		trigger:"None",
		location:"south screen from Forest toilet",
		requirement:"Talk to him 3 times and he will fight you - win the fight.",
		unlocks:"upgrades meat farm to yield giant meat, sells you giant meat for 500 bits each",
		angemonTip:"Vegetation Digimon are in the forest. The closer they are the harder they are to see.",
		enemies:[
			{
				name:"Palmon",
				hp:900,
				mp:1600,
				off:180,
				def:130,
				spd:70,
				brn:100,
				bits:1000,
				item:"Brain Chip",
				dropChance:100,
				moves:[{name:"Poison Claw",chance:44.44},{name:"Poison Powder",chance:33.33},{name:"Water Blit",chance:22.22}],
				finisher:"Poison Ivy"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Coelamon",
		level:"Champion",
		maps:[],
		recruitMap:"MAYO05",
		region:"Native Forest",
		trigger:"16:00-19:59",
		location:"southeast from Kunemon's bed",
		requirement:"Go to his screen at dusk (16:00-19:59) and he will swim there. Talk to him, he will bring you to the jungle. Go north and over the now repaired Digimon bridge and go back where you found Coelamon the first time.<br />Talk to him again and he'll join the town.",
		unlocks:"Shop",
		angemonTip:"An old-timer in the river is waiting for someone.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Seadramon",
		level:"Champion",
		maps:[],
		recruitMap:"MAYO06",
		region:"Native Forest",
		trigger:"08:00-08:59/17:00-17:59 & have fishing rod",
		location:"Dragon Lake Island",
		requirement:"Go to the spot between 08:00 and 08:59 or between 17:00 and 17:59 and try to fish the big, fast moving fish.<br />It might take some time until he takes the bait. Once he nibbles you have to get the timing right, as a rule of thumb you should let the swimmer bob 3 times before pressing X.<br />Once you got he hooked you have to be patient - hold the tension bar in the middle and you'll eventually catch it. Chose the Friend option to recruit it.",
		unlocks:"He gives you a flute you can use at the coast of Dragon Lake by pressing X to get you to Beetle Island",
		angemonTip:"Some Insectoid Digimon live beyond Dragon Eye Lake. Go fishing there.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Etemon",
		level:"Ultra",
		maps:[],
		recruitMap:"MAYO04A",
		region:"Native Forest",
		trigger:"50pp",
		location:"South from Kunemon's Bed when having 50+ Prosperity. His appearance is triggered by interacting with the door and does 30% damage of the max HP of your Digimon.",
		requirement:"Win the fight against him.",
		unlocks:"Sells the Etemon evolution item at Digibridge",
		angemonTip:"There might be Digimon that live in trees, but who knows?",
		enemies:[
			{
				name:"Etemon",
				hp:5600,
				mp:5600,
				off:700,
				def:580,
				spd:530,
				brn:600,
				bits:7777,
				item:"Brain Chip",
				dropChance:100,
				moves:[{name:"Dynamite Kick",chance:44.44},{name:"Buster Dive",chance:22.22},{name:"War Cry",chance:33.33}],
				finisher:"Dark Network & Concert Crush"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:50,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Ninjamon",
		level:"Champion",
		maps:[],
		recruitMap:"MAYO08A",
		region:"Native Forest",
		trigger:"Secret Shop",
		location:"Digimon Bridge, when walking to Kunemon's bed with one Digimon that works in the secret shop recruited. The big shop building is not required.",
		requirement:"win the fight against him",
		unlocks:"Gives you information about Items when you talk to him",
		angemonTip:"When rumors about you spread, you should come back.",
		enemies:[
			{
				name:"Ninjamon",
				hp:3800,
				mp:3500,
				off:620,
				def:210,
				spd:350,
				brn:250,
				bits:2048,
				item:"Quick Chip",
				dropChance:100,
				moves:[{name:"Magma Bomb",chance:44.44},{name:"Dynamite Kick",chance:33.33},{name:"Charm Perfume",chance:22.22}],
				finisher:"Iga School Knife Throw"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Numemon","Mojyamon","Devimon","Mamemon"],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Kuwagamon",
		level:"Champion",
		maps:[],
		recruitMap:"BETL04",
		region:"Beetle Island",
		trigger:"Seadramon",
		location:"Bettle Island, left training hall",
		requirement:"Talk to him and chose the 2nd option",
		unlocks:"improves training of HP, Offense and Brains in Green Gym",
		angemonTip:"",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Seadramon"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Kabuterimon",
		level:"Champion",
		maps:[],
		recruitMap:"BETL03",
		region:"Beetle Island",
		trigger:"Seadramon & Greymon",
		location:"Bettle Island, right training hall once you've recruited Greymon",
		requirement:"Talk to him and chose the 2nd option",
		unlocks:"improves training of MP, Defense and Speed in Green Gym",
		angemonTip:"",
		enemies:[],
		recruitTriggerAnd:["Seadramon","Greymon"],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Greymon",
		level:"Champion",
		maps:[],
		recruitMap:"TWNA02",
		region:"File City",
		trigger:"15pp & leave Jijimon's hut",
		location:"When you talk to Jijimon and leave his house with a prosperity rate of 15 or higher.",
		requirement:"win the fight against him",
		unlocks:"Arena",
		angemonTip:"Some Digimon may know about you and challenge you.",
		enemies:[
			{
				name:"Greymon",
				hp:4800,
				mp:3800,
				off:630,
				def:340,
				spd:360,
				brn:200,
				bits:2900,
				item:"Off. Chip",
				dropChance:100,
				moves:[{name:"Magma Bomb",chance:33.33},{name:"Red Inferno",chance:22.22},{name:"Dynamite Kick",chance:44.44}],
				finisher:"Mega Flame"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:15,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Airdramon",
		level:"Champion",
		maps:[],
		recruitMap:"TWNA02",
		region:"File City",
		trigger:"50pp & leave Jijimon's hut",
		location:"When you talk to Jijimon and leave his house with a prosperity rate of 50 or higher. He'll deal 10% damage of your max HP before the fight starts.",
		requirement:"win the fight against him and he'll join the town after you beat Machinedramon.",
		unlocks:"Fortune teller in arena",
		angemonTip:"",
		enemies:[
			{
				name:"Airdramon",
				hp:4400,
				mp:3900,
				off:610,
				def:320,
				spd:340,
				brn:200,
				bits:2600,
				item:"Brain Chip",
				dropChance:0,
				moves:[{name:"Megalo Spark",chance:33.33},{name:"Confused Storm",chance:44.44},{name:"Hurricane",chance:22.22}],
				finisher:"Spnning Needle"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:50,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Piximon",
		level:"Ultra",
		maps:[],
		recruitMap:"TROP01",
		region:"Tropical Jungle",
		trigger:"3% chance",
		location:"2nd jungle screen when coming from the Digibridge",
		requirement:"win the fight against him",
		unlocks:"sells the 'Training Manual' for 50'000 bits in the Item Shop, he has a 20% of spawning there each time you enter it.",
		angemonTip:"A rare Digimon appears in a jungle and challenges others to fight.",
		enemies:[
			{
				name:"Piximon",
				hp:5200,
				mp:4600,
				off:680,
				def:460,
				spd:660,
				brn:600,
				bits:3600,
				item:"MP Chip",
				dropChance:100,
				moves:[{name:"Danger Sting",chance:50},{name:"Bug",chance:12.5},{name:"Confused Storm",chance:37.5}],
				finisher:"Bit Bomb"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Mamemon",
		level:"Ultra",
		maps:[],
		recruitMap:"MIHA01",
		region:"Mt. Panorama",
		trigger:"3% chance",
		location:"Top of Mt. Panorama",
		requirement:"win the fight against him",
		unlocks:"Secret Shop (sells stat Disks)",
		angemonTip:"On the top of Mt.Panorama, a Digimon will challenge you to fight if you see him.",
		enemies:[
			{
				name:"Mamemon",
				hp:4800,
				mp:4600,
				off:650,
				def:480,
				spd:520,
				brn:550,
				bits:2800,
				item:"Quick Chip",
				dropChance:100,
				moves:[{name:"Megaton Punch",chance:50},{name:"Buster Dive",chance:12.5},{name:"Full Potential",chance:37.5}],
				finisher:"Smiley Bomb"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"MetalMamemon",
		level:"Ultra",
		maps:[],
		recruitMap:"FACT02",
		region:"Factorial Town",
		trigger:"3% chance",
		location:"2nd screen of factorial town when entering via Whamon",
		requirement:"win the fight against him",
		unlocks:"Curling enemy (special prices: Giromon, Mamemon, MetalMamemon and Piximon evolution items)",
		angemonTip:"In an Iron City to the west a rare Digimon may appear and challenge others to fight.",
		enemies:[
			{
				name:"MetalMamemon",
				hp:5600,
				mp:4800,
				off:630,
				def:580,
				spd:500,
				brn:500,
				bits:4000,
				item:"Def. Chip",
				dropChance:100,
				moves:[{name:"Pulse Laser",chance:44.44},{name:"Metal Sprinter",chance:33.33},{name:"All Range Beam",chance:22.22}],
				finisher:"Energy Bomb"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Whamon"],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Drimogemon",
		level:"Champion",
		maps:[],
		recruitMap:"TUNN09",
		region:"Lava Cave",
		trigger:"Beat Meramon & talk & wait 3 days",
		location:"Entrance, Gear Savanna Side",
		requirement:"After you've recruited Meramon the recruitable Drimogemon will appear in the lower part of the cave.<br />Talking to him triggers another 3 ingame days event to open a path to Gear Savanna. Once he finished that he'll join the town once you talk to him again.",
		unlocks:"Treasure Hunter shop - (also: Meramon's Cave, Path through Drill Tunnel to Gear Savanna)",
		angemonTip:"You should ask hard working Digimon to come to the city, once their duties are over.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Meramon"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Meramon",
		level:"Champion",
		maps:["TUNN04","TUNN05"],
		recruitMap:"TUNN08",
		region:"Drill Tunnel",
		trigger:"Fight Drimogemon & carry dirt 10 times/wait 5 days (every set of 2 dirtcarries reduces the waiting time by 1 day)",
		location:"Meramon's cave, which has to be opened by Drimogemon first",
		requirement:"First fight the Drimogemon in the kitchen (left screen from 'hub' screen), this unlocks the Drimogemon on the right screen to drill the tunnel.<br />Once you talked to him it takes 5 ingame days for him to dig the tunnel - the time can be shortened by carrying dirt for him.<br />When he is finished you have to move a rock for him that unlocks Meramon's cave - you need a champion for that. After that just win the fight against him",
		unlocks:"Restaurant, Path to Gear Savanna over Mt. Panorama",
		angemonTip:"Lava flows inside of Mt.Panorama. Some Digimon love the heat.",
		enemies:[
			{
				name:"Drimogemon",
				hp:1400,
				mp:2400,
				off:280,
				def:140,
				spd:140,
				brn:100,
				bits:1200,
				item:"",
				dropChance:0,
				moves:[{name:"Sonic Jab",chance:44.44},{name:"Dynamite Kick",chance:33.33},{name:"Megaton Punch",chance:22.22}],
				finisher:"Drill Spin"
			},
			{
				name:"Meramon",
				hp:2600,
				mp:2800,
				off:320,
				def:160,
				spd:180,
				brn:200,
				bits:2400,
				item:"Off. Chip",
				dropChance:100,
				moves:[{name:"Magma Bomb",chance:33.33},{name:"Heat Laser",chance:22.22},{name:"Dynamite Kick",chance:44.44}],
				finisher:"Fireball"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:2,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Elecmon",
		level:"Rookie",
		maps:[],
		recruitMap:"GIAS02",
		region:"Gear Savanna",
		trigger:"None",
		location:"Top left screen of Gear Savanna at the entrance to Factorial Town",
		requirement:"Talk 3 times to him, you'll get 20% of your max HP as damage every time you talk to him",
		unlocks:"Electricity in the town, adding lights that turn on at night time",
		angemonTip:"In Gear Savanna, there is a Digimon who loves electricity.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Patamon",
		level:"Rookie",
		maps:[],
		recruitMap:"GIAS03",
		region:"Gear Savanna",
		trigger:"None",
		location:"Center top screen of the area",
		requirement:"Win 3 times in a row against him",
		unlocks:"Shop",
		angemonTip:"Gear Savanna suits Digimon who can't fly high. You should search there.",
		enemies:[
			{
				name:"Patamon",
				hp:1000,
				mp:1000,
				off:150,
				def:100,
				spd:100,
				brn:100,
				bits:500,
				item:"MP Floppy",
				dropChance:20,
				moves:[{name:"Dynamite Kick",chance:44.44},{name:"Wind Cutter",chance:33.33},{name:"Spinning Shot",chance:22.22}],
				finisher:"Boom Bubble"
			},
			{
				name:"Patamon",
				hp:1000,
				mp:1000,
				off:150,
				def:100,
				spd:100,
				brn:100,
				bits:500,
				item:"MP Floppy",
				dropChance:20,
				moves:[{name:"Dynamite Kick",chance:44.44},{name:"Wind Cutter",chance:33.33},{name:"Spinning Shot",chance:22.22}],
				finisher:"Boom Bubble"
			},
			{
				name:"Patamon",
				hp:1000,
				mp:1000,
				off:150,
				def:100,
				spd:100,
				brn:100,
				bits:500,
				item:"MP Floppy",
				dropChance:20,
				moves:[{name:"Dynamite Kick",chance:44.44},{name:"Wind Cutter",chance:33.33},{name:"Spinning Shot",chance:22.22}],
				finisher:"Boom Bubble"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:3,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Biyomon",
		level:"Rookie",
		maps:[],
		recruitMap:"GIAS04",
		region:"Gear Savanna",
		trigger:"None",
		location:"the screen south from Patamon",
		requirement:"Talk to Biyomon, she will run away, talk to her again and look for a spot that opens a chat menu (it's close to the point where Biyomon stood) and pick 'Wait', telling your Digimon to hunt Biyomon.<br />This one is heavy RNG, so continue to do that until you succeed.",
		unlocks:"Shop",
		angemonTip:"Gear Savanna suits Digimon who can't fly high. You should search there.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Sukamon",
		level:"Champion",
		maps:[],
		recruitMap:"GOMI02",
		region:"Gear Savanna",
		trigger:"None",
		location:"Mt. Trash",
		requirement:"Talk to the Sukamon above the MP training. You won't get a join message, but you'll see him near the toilet sometimes.",
		unlocks:"Nothing",
		angemonTip:"",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Leomon",
		level:"Champion",
		maps:["GIAS09","TUNN03_2"],
		recruitMap:"GIAS07",
		region:"Gear Savanna",
		trigger:"45pp & Meramon",
		location:"South from Mt. Trash you'll find a Patamon chased by a Goburimon that gets rescued by Leomon. The screen left to that you can find Leomon.<br />Once you have the table and talk to Leomon for him to join the town.",
		requirement:"You have to get the stone table from Leomon's Cave inside the Drill Tunnel (south from the hub). The cave gets opened once you have 45 prosperity and Meramon in the town.",
		unlocks:"Nothing",
		angemonTip:"There is supposedly a buried old tablet, but someone has to dig it up.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Meramon"],
		fight:0,
		prosperityTrigger:45,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Vegiemon",
		level:"Champion",
		maps:["TWNA02"],
		recruitMap:"TROP03",
		region:"Tropical Jungle",
		trigger:"Wait until the 15th of the month",
		location:"Exit the toilet screen to the right",
		requirement:"On day 15 of every year you can collect a Rain Plant near the meat field. Talk to Tanemon afterwards. Once you did that you'll find a small plant in the target screen.<br />Interact with the plant and use the Rain Plant. Vegiemon will appear and ask a question, he'll join the town regardless of your answer.",
		unlocks:"upgrades meat farm to yield sirloin, sells you Supercarrot and Hawk Raddish",
		angemonTip:"A secret lies in the flower bed of the city. Ask a plant about another plant.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Palmon"],
		fight:0,
		prosperityTrigger:10,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Centarumon",
		level:"Champion",
		maps:[],
		recruitMap:"TROP06",
		region:"Tropical Jungle/Amida Forest",
		trigger:"None",
		location:"If you keep going right from the DigiBridge you'll end up in Amida Forest (Right -> Right -> Up)",
		requirement:"You have to find the exist to the maze. It's an Amida kuji, so you have to switch the lane whenever possible.<br />The exit is random, so you might fail getting the right exit a few times. Walking into the wrong door ends up with you being teleported back to the start.<br />If you don't switch the lane or try to go back Centarumon will shoot you, dealing 50% of your max HP as damage. If your HP reach 1, you'll get teleported back and you have to heal in order to continue.<br />Once you made it to the right exit Centarumon will join the city and open a path to the Ancient Dino Region.",
		unlocks:"A Clinic where you can heal and rest your Digimon and buy bandages as well as medicine.",
		angemonTip:"In Tropical Jungle there is a maze-like forest. A strong Digimon guards it.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Tyrannomon",
		level:"Champion",
		maps:["KODA07"],
		recruitMap:"KODA00",
		region:"Ancient Dino Region",
		trigger:"Centarumon",
		location:"First screen after Amida Forest",
		requirement:"He'll attack you once you walk a few steps into the Ancient Dino Region, win the fight.<br />This allows you to visit the whole region until you meet him in front of the Speedy Time Zone. Talk to him and he lets you enter it. At the bone tunnel, there is a hidden passage in the top left.<br />There you'll find Meteormon. Beat him in a fight and you can recruit Tyrannomon afterwards.",
		unlocks:"Restaurant",
		angemonTip:"The Ancient Dino Region is dangerous, but it's best to check it out.",
		enemies:[
			{
				name:"Tyrannomon",
				hp:3100,
				mp:2800,
				off:380,
				def:220,
				spd:210,
				brn:200,
				bits:2500,
				item:"HP Chip",
				dropChance:100,
				moves:[{name:"Megaton Punch",chance:40},{name:"Buster Dive",chance:25},{name:"Tremar",chance:20},{name:"War Cry",chance:15}],
				finisher:""
			},
			{
				name:"Meteormon",
				hp:3400,
				mp:2800,
				off:400,
				def:210,
				spd:220,
				brn:150,
				bits:2800,
				item:"HP Chip",
				dropChance:100,
				moves:[{name:"Magma Bomb",chance:40},{name:"Meltdown",chance:10},{name:"Megaton Punch",chance:40},{name:"Tremar",chance:10}],
				finisher:""
			}

		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Centarumon"],
		fight:2,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Betamon",
		level:"Rookie",
		maps:[],
		recruitMap:"TROP04",
		region:"Tropical Jungle/Mangrove Region",
		trigger:"None",
		location:"Head to the right of the screen where Coelamon brings you but exit the screen on the top.",
		requirement:"Talk to him and he'll join the town.",
		unlocks:"Shop",
		angemonTip:"There is a Digimon who loves warm water shores.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Bakemon",
		level:"Champion",
		maps:[],
		recruitMap:"DGHA02",
		region:"Overdell Cemetery",
		trigger:"None",
		location:"Head straight north from the point where Coelamon brought you until you enter the Overdell Cemetery",
		requirement:"Talk to Bakemon and answer Yes, Yes, No and he'll join the town.",
		unlocks:"Nothing",
		angemonTip:"Graveyards have ghosts. Ghosts love talking to you.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Unimon",
		level:"Champion",
		maps:[],
		recruitMap:"MIHA05",
		region:"Mt. Panorama",
		trigger:"Recruit Centarumon and talk to him once. Beat Meramon or walk all the way around the island",
		location:"Second screen when you enter Mt. Panorama via Native Forest after you recruited Centarumon and talked to him once.",
		requirement:"Give him an healing Item (e.g. sm. recovery Floppy) and he'll join the town",
		unlocks:"Shop",
		angemonTip:"You might meet a Digimon with wings that can fly over Mt.Panorama in one flap.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Centarumon"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Vademon",
		level:"Ultra",
		maps:[],
		recruitMap:"MIHA06",
		region:"Mt. Panorama",
		trigger:"45pp & Shellmon",
		location:"Chose the right exit from Unimon",
		requirement:"1. Go to his location, step on the marks on the floor, a textbox should appear.<br />2. Read Shellmon's bulletin board (Entry 2), go back to the location and step on the marks on the floor, a textbox should appear.<br />3. With 45pp+, read Shellmon's bulletin board (Entry 8), go back to the location and stop on the marks on the floor - Vademon should appear and join the town.",
		unlocks:"Restaurant",
		angemonTip:"There is an Alien Digimon. You may meet him someday.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Shellmon"],
		fight:0,
		prosperityTrigger:45,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Gabumon",
		level:"Rookie",
		maps:[],
		recruitMap:"MIST06",
		region:"Misty Trees",
		trigger:"None",
		location:"When you enter Misty Trees from Geko Swamp, exit the screen on the left. Gabumon is hiding behind a tree.",
		requirement:"win the fight against him",
		unlocks:"Improves Treasure Hunter shop, increases chance to get a valuable item (evolution item/chip).",
		angemonTip:"Misty Trees is perfect for hiding. Your job is also to guide Digimon in hiding.",
		enemies:[
			{
				name:"Gabumon",
				hp:2000,
				mp:2600,
				off:320,
				def:220,
				spd:190,
				brn:150,
				bits:1000,
				item:"MP Chip",
				dropChance:0,
				moves:[{name:"Dynamite Kick",chance:44.44},{name:"Megaton Punch",chance:33.33},{name:"War Cry",chance:22.22}],
				finisher:"Blue Blaster"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Kokatorimon",
		level:"Champion",
		maps:[],
		recruitMap:"MIST03",
		region:"Misty Trees",
		trigger:"4:00-6:59",
		location:"When you enter Misty Trees from Geko Swamp, exit the screen 2 times on the right. Kokatorimon will be there in the early morning between 4:00 and 6:59.",
		requirement:"win the fight against him",
		unlocks:"A statue near the toilet",
		angemonTip:"In Misty Trees, an early rising Digimon may appear.",
		enemies:[
			{
				name:"Kokatorimon",
				hp:4200,
				mp:4800,
				off:600,
				def:240,
				spd:360,
				brn:100,
				bits:2800,
				item:"Def. Chip",
				dropChance:100,
				moves:[{name:"Dynamite Kick",chance:55.56},{name:"War Cry",chance:11.11},{name:"Megalo Spark",chance:33.33}],
				finisher:"Frozen Fire Shot"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Monzaemon",
		level:"Ultra",
		maps:["OMOC02","OMOC08"],
		recruitMap:"OMOC03",
		region:"Toy Town",
		trigger:"Raise a Numemon",
		location:"Monzaemon Costume House",
		requirement:"You need a Monzaemon as your partner Digimon. You can easily get one by using the Monzaemon costume in the left house of Toy Town while having a Numemon, alternatively you can get the Monzaemon evolution item by trading Hagurumon, ToyAgumon and WaruMonzaemon cards with ClearAgumon.<br />Talk to the Tinmon in the right house, once you finished go to the big villa in the middle and you should be able to open the door. Follow the path until you find 2 boxes.<br />You'll have to fight WaruMonzaemon there, who gives you a Gear Item. Bring this item back to the Tinmon in the right house and you're done.",
		unlocks:"Monzaemon costume in the back of Jijimon's house. Doesn't have any use.",
		angemonTip:"",
		enemies:[
			{
				name:"WaruMonzaemon",
				hp:5200,
				mp:2600,
				off:680,
				def:340,
				spd:380,
				brn:100,
				bits:3500,
				item:"HP Chip",
				dropChance:50,
				moves:[{name:"Megaton Punch",chance:40},{name:"Buster Dive",chance:20},{name:"Muscle Charge",chance:10},{name:"Thunder Justice",chance:30}],
				finisher:""
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Andromon",
		level:"Ultra",
		maps:[],
		recruitMap:"FACT06",
		region:"Factorial Town",
		trigger:"Giromon & Numemon",
		location:"In the middle of factorial town, there is a small house where Andromon is in.",
		requirement:"Talk to him once you've beating Giromon, that will allow you to recruit Numemon. Talk to him again after you've recruited Numemon.<br />Now, once you have the large shop, restaurant, hospital and gym and visited the screen once you should be able to recruit by talking twice to him again.",
		unlocks:"Nothing",
		angemonTip:"",
		enemies:[],
		recruitTriggerAnd:["Giromon","Numemon"],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Giromon",
		level:"Ultra",
		maps:[],
		recruitMap:"FACT08B",
		region:"Factorial Town",
		trigger:"12:00-12:01/24:00-00:01",
		location:"When leaving the screen with Andromon's house on the right side at 12 a.m. / p.m. you can enter the factory. Enter the left door on the 2nd screen.",
		requirement:"win the fight against him. You can recruit him by talking to him again once you have recruited Andromon.",
		unlocks:"Giromon's Jukebox in the restaurant. WARNING, in NTSC versions the Jukebox is bugged and causes your game to crash!",
		angemonTip:"When Android Digimon breaks, he can repair himself completely quickly.",
		enemies:[
			{
				name:"Giromon",
				hp:5700,
				mp:4800,
				off:690,
				def:450,
				spd:490,
				brn:300,
				bits:3500,
				item:"Def. Chip",
				dropChance:100,
				moves:[{name:"Delete Program",chance:33.33},{name:"Reverse Prog",chance:33.33},{name:"DG Dimension",chance:33.33}],
				finisher:"Deadly Bomb"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Whamon"],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Numemon",
		level:"Champion",
		maps:[],
		recruitMap:"FACT11B",
		region:"Factorial Town",
		trigger:"Giromon",
		location:"North the central screen there is a ladder that leads to the sewers.",
		requirement:"After you've beaten Giromon and talked to Andromon the fog in the sewers should be gone. Talk to Numemon and win the fight against him.",
		unlocks:"Secret shop (sells Enemy Bell and Enemy Repel)",
		angemonTip:"Digimon are also in damp places such as sewers. Help them in their problems.",
		enemies:[
			{
				name:"Numemon",
				hp:200,
				mp:500,
				off:40,
				def:50,
				spd:50,
				brn:50,
				bits:100,
				item:"MP Chip",
				dropChance:100,
				moves:[{name:"Odor Spray",chance:50},{name:"Ult Poop Hell",chance:50}],
				finisher:"Party time"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Giromon"],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"SkullGreymon",
		level:"Ultra",
		maps:[],
		recruitMap:"SAIB03",
		region:"Grey Lord's Mansion",
		trigger:"35pp & Shellmon",
		location:"Underground Lab",
		requirement:"Enter the Mansion, use the door on the right side of the stairs, keep going left until you reach a large room with a fireplace - talk to the fireplace and you'll find the mansion key.<br />Head back to the room under the stairs but this time enter the upper door. Behind the 2 Rockmon is a spot where you'll fall though (you get 30% of your max HP damage).<br />Use the upper door and talk to the coffin, which opens up the hidden Room where Myotismon is. Talk to him and he'll give you the fridge key and a quest to bring him meat.<br />Go back to the screen where the 3 Soulmon are and talk to the fridge. After that leave the Mansion and you'll find the 'Steak' in front of it. Bring it to Myotismon and you're done for now.<br />Once you have 35 prosperity points read the message about Myotismon at Shellmon's bulletin board and head back to the mansion.<br />Visit the hidden room and the dining room each in which a dialogue will trigger. Then head to the exit of the mansion again and a cutscene with Devimon will be triggered.<br />After the cutscene you can enter the lower right door which was previously locked, where you'll find the secret lab with SkullGreymon. Defeat him.<br />Once you've defeated SkullGreymon you can talk to Myotismon in the room before and finish the recruitment. Talk to him twice!",
		unlocks:"Fights in Arena",
		angemonTip:"Myotismon is missing. Follow the clues that are in his mansion.",
		enemies:[
			{
				name:"SkullGreymon",
				hp:5800,
				mp:4800,
				off:650,
				def:340,
				spd:380,
				brn:150,
				bits:3500,
				item:"Off. Chip",
				dropChance:100,
				moves:[{name:"Dynamite Kick",chance:50},{name:"Buster Dive",chance:38.89},{name:"War Cry",chance:11.11}],
				finisher:"Dark Shot"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Shellmon"],
		fight:1,
		prosperityTrigger:35,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Monochromon",
		level:"Champion",
		maps:[],
		recruitMap:"GCAN11",
		region:"Great Canyon",
		trigger:"None",
		location:"The Shop next to the Toilet in the first screen.",
		requirement:"When talking to him he'll let you work in his Shop to test if you're 'worthy'. If you manage to have over 3072 Bits profit he'll join the town.<br />The Shop Minigame is very RNG intensive and hard. Goburimon and Mucho are usually easy customers (you can often sell them expensive stuff, even if they're unhappy)<br />while Gotsumon and Weedmon have to treated carefully. This minigame costs you 8h of time and gives you a bit of money.",
		unlocks:"Shop",
		angemonTip:"In Great Canyon, there is a shop owned by a Digimon.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Birdramon",
		level:"Champion",
		maps:[],
		recruitMap:"GCAN10",
		region:"Great Canyon",
		trigger:"None",
		location:"When you chose the right path you'll eventually come to an elevator. Chose UP and you'll end up a Birdramon's nest.",
		requirement:"Walk into the nest and Birdramon will appear. Win the fight and she will join your town.",
		unlocks:"Birdra Transport, the quick travel System of this game",
		angemonTip:"On the peak of Great Canyon, a Bird Digimon lives.",
		enemies:[
			{
				name:"Birdramon",
				hp:3700,
				mp:3500,
				off:490,
				def:200,
				spd:340,
				brn:200,
				bits:1000,
				item:"",
				dropChance:0,
				moves:[{name:"Prominence Beam",chance:100}],
				finisher:"Meteor Wing"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Shellmon",
		level:"Champion",
		maps:[],
		recruitMap:"GCAN04",
		region:"Great Canyon",
		trigger:"Ogremon 1",
		location:"Great Canyon Bridge",
		requirement:"After you've beaten Ogremon in his Fortress, use the elevator from the last room and follow the path until you hear someone calling for help.<br />Head back to Ogre Fortress and go to the elevator that can lead you to Birdramon's nest - press one times UP. Leave the Canyon in direction Freezeland and in the first Freezeland screen<br />you'll find another bridge to the Canyon. Use it and you'll find Shellmon who will join your town once you talk to him.",
		unlocks:"Shellmon's Bulleting Board. Contains some information as well as hints and trigger for certain recruitments.",
		angemonTip:"Grand Canyon is like a maze. Once entered, it's hard to leave.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Ogremon2"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Penguinmon",
		level:"Rookie",
		maps:[],
		recruitMap:"FRZL15",
		region:"Freezeland",
		trigger:"None",
		location:"Head to the screen with the guidepost and follow the right way and leave the first screen as far north as you can on the right side.",
		requirement:"Talk with Penguinmon and he'll challenge you to a match of Curling. Win the game and he'll join the city. If you lose you can play again, but you have to bring him any fish.<br />The AI is at sometimes a bit stupid.",
		unlocks:"Curling in the Arena of your town.",
		angemonTip:"In Freezeland, there are Digimons that live in caves and invite others in.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Mojyamon",
		level:"Champion",
		maps:["FRZL15"],
		recruitMap:"FRZL14",
		region:"Freezeland",
		trigger:"None",
		location:"There are 3 Mojyamon, all can be reached from the same screen where you can enter Penguinmon's screen. (Lower right side and south side)",
		requirement:"Each Mojyamon offers 3 trades and the last Mojyamon you traded with will join your town once you've traded all trades at least once.<br />You'll need the following Items: Digimushroom, Supercarrot, Happymushroom, Giant Meat, Black Trout, Hispeed Disk, Omnipotent, med. recovery and Digianchovy.",
		unlocks:"Secret shop - sells Rest pillow (more sleep regen) and health shoes (HP+MP regen while walking)",
		angemonTip:"Help Digimon that love to collect things. Try going to Freezeland.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Whamon",
		level:"Champion",
		maps:[],
		recruitMap:"FRZL16",
		region:"Freezeland",
		trigger:"Ogremon 2",
		location:"Screen to the left of Mojyamon hub screen",
		requirement:"After you've beaten Ogremon in Ogre Fortress, leave the screen that leads to Penguinmon and Mojyamon on the left and head straight down the ice pier.<br />You'll find Whamon there who will take you to a secret cave that contains the 3rd phase of the Ogremon recruitment, after which Whamon will join.",
		unlocks:"Fast travel to Factorial Town and the secret cave (you can find an evolution item for Digitamamon there)",
		angemonTip:"A huge shadow appears along the coasts of Freezeland. Perhaps it is a Digimon.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Ogremon2"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Angemon",
		level:"Champion",
		maps:["ICSA06"],
		recruitMap:"ICSA01",
		region:"Freezeland",
		trigger:"None",
		location:"Blue Light Screen",
		requirement:"Enter the Ice Sanctuary and talk to statue. After that go in the direction of the exit and your Digimon will open the hidden passge.<br />Once your down the stairs, stay on the right wall and you'll find a secret entrance in the first small room.",
		unlocks:"He'll give you hints about the Digimon you haven't recruited yet.",
		angemonTip:"",
		enemies:[
			{
				name:"Hyogamon",
				hp:2900,
				mp:4100,
				off:570,
				def:310,
				spd:230,
				brn:200,
				bits:1200,
				item:"Sirloin",
				dropChance:10,
				moves:[{name:"Giga Freeze",chance:30},{name:"Ice Needle",chance:20},{name:"Sonic Jab",chance:20},{name:"Buster Dive",chance:30}],
				finisher:""
			},
			{
				name:"Hyogamon",
				hp:2900,
				mp:4100,
				off:570,
				def:310,
				spd:230,
				brn:200,
				bits:1200,
				item:"Sirloin",
				dropChance:10,
				moves:[{name:"Giga Freeze",chance:30},{name:"Ice Needle",chance:20},{name:"Sonic Jab",chance:20},{name:"Buster Dive",chance:30}],
				finisher:""
			},
			{
				name:"Icemon",
				hp:2600,
				mp:3200,
				off:510,
				def:340,
				spd:200,
				brn:150,
				bits:1200,
				item:"Medium MP",
				dropChance:10,
				moves:[{name:"Megaton Punch",chance:40},{name:"Giga Freeze",chance:20},{name:"Ice Needle",chance:40}],
				finisher:""
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Frigimon",
		level:"Champion",
		maps:[],
		recruitMap:"FRZL18",
		region:"Freezeland",
		trigger:"Sick Digimon weak against cold",
		location:"Igloo Screen",
		requirement:"Take a Digimon that doesn't like cold and make it sick. Easiest way to get sick is using Moldy Meat (can be bought at the vending machine in Ancient Dino Region).<br />Once sick you have to go to a certain spot to trigger the event. So just walk around a bit in Freezeland till your Digimon 'passes out'.<br />After that get another Digimon, that doesn't not like the cold and talk to Frigimon again, making him joining the city.<br /> The Digimon you can use for this are Botamon, Koromon, Agumon, Greymon, Tyrannomon, Meramon, Punimon, Tsunomon, Kabuterimon, Birdramon, Poyomon, Tokomon, Kunemon, Yuramon, Tanemon, Monochromon and Kuwagamon.",
		unlocks:"Restaurant",
		angemonTip:"Taking a Digimon, who loves hot places, to a cold place is against the rules, but...",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Garurumon",
		level:"Champion",
		maps:[],
		recruitMap:"FRZL08",
		region:"Freezeland",
		trigger:"None",
		location:"South from Frigimon's house",
		requirement:"Fight him and win the fight. He'll challenge you again for 4 p.m. the next day. If you miss that time you can still fight him, but he'll have more HP then.<br />The 2nd fight has to be done without items or command, so having a strong Digimon is recommended!",
		unlocks:"Restaurant",
		angemonTip:"In Freezeland there are many Digimon who'll come with you. Go to the west.",
		enemies:[
			{
				name:"Garurumon",
				hp:4200,
				mp:4500,
				off:580,
				def:320,
				spd:240,
				brn:150,
				bits:3200,
				item:"HP Chip",
				dropChance:100,
				moves:[{name:"War Cry",chance:11.12},{name:"Giga Freeze",chance:44.44},{name:"Ice Statue",chance:44.44}],
				finisher:"Howling Blaster"
			},
			{
				name:"Garurumon",
				hp:2100,
				mp:4500,
				off:580,
				def:320,
				spd:240,
				brn:150,
				bits:3200,
				item:"HP Chip",
				dropChance:100,
				moves:[{name:"War Cry",chance:11.12},{name:"Giga Freeze",chance:44.44},{name:"Ice Statue",chance:44.44}],
				finisher:"Howling Blaster"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:2,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Nanimon1",
		level:"Champion",
		maps:[],
		recruitMap:"KODA07",
		region:"Ancient Speedy Region",
		trigger:"Tyrannomon",
		location:"Meteormon Screen",
		requirement:"Nanimon appears at 5 locations after certain recruitments are done. There is no set order you have to visit these places.<br />1. Ogre Fortress, last room - after Phase 3 of Ogremon recruitment<br />2. Toy Town, last room - after Monzaemon recruitment<br />3. Speedy Dino Region, where Meteormon was - after Tyrannomon recruitment<br />4. Leomon's Cave - after Leomon recruitment<br />5. Factorial Town Sewers - after Andromon recruitment",
		unlocks:"The first time you find him he'll drop a keychain that increases you Inventory to 20 slots, the last time you find him he'll drop a Key Chain, increasing your Inventory to 30 slots.",
		angemonTip:"There is a Mythical Animal Digimon. He is in a house that has lost its owners.<br>You must keep looking for Nanimon until you get the real treasure.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Tyrannomon"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Nanimon2",
		level:"Champion",
		maps:[],
		recruitMap:"OGRE03",
		region:"Ogre Fortress",
		trigger:"Ogremon 3",
		location:"Living Room",
		requirement:"Visit Ogre Fortress, last room - after Phase 3 of Ogremon recruitment",
		unlocks:"The first time you find him he'll drop a keychain that increases you Inventory to 20 slots, the last time you find him he'll drop a Key Chain, increasing your Inventory to 30 slots.",
		angemonTip:"There is a Mythical Animal Digimon. He is in a house that has lost its owners.<br>You must keep looking for Nanimon until you get the real treasure.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Ogremon3"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Nanimon3",
		level:"Champion",
		maps:[],
		recruitMap:"FACT11B",
		region:"Sewer",
		trigger:"Andromon",
		location:"Numemon Screen",
		requirement:"Visit Factorial Town Sewers - after Andromon recruitment",
		unlocks:"The first time you find him he'll drop a keychain that increases you Inventory to 20 slots, the last time you find him he'll drop a Key Chain, increasing your Inventory to 30 slots.",
		angemonTip:"There is a Mythical Animal Digimon. He is in a house that has lost its owners.<br>You must keep looking for Nanimon until you get the real treasure.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Andromon"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Nanimon4",
		level:"Champion",
		maps:[],
		recruitMap:"LEOM01",
		region:"Leomon's Ancestor Cave",
		trigger:"Leomon",
		location:"Statue Room",
		requirement:"Visit Leomon's Cave - after Leomon recruitment",
		unlocks:"The first time you find him he'll drop a keychain that increases you Inventory to 20 slots, the last time you find him he'll drop a Key Chain, increasing your Inventory to 30 slots.",
		angemonTip:"There is a Mythical Animal Digimon. He is in a house that has lost its owners.<br>You must keep looking for Nanimon until you get the real treasure.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Leomon"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Nanimon5",
		level:"Champion",
		maps:[],
		recruitMap:"OMOC08",
		region:"Toy Mansion",
		trigger:"Monzaemon",
		location:"WaruMonzaemon Screen",
		requirement:"Visit Toy Town, last room - after Monzaemon recruitment",
		unlocks:"The first time you find him he'll drop a keychain that increases you Inventory to 20 slots, the last time you find him he'll drop a Key Chain, increasing your Inventory to 30 slots.",
		angemonTip:"There is a Mythical Animal Digimon. He is in a house that has lost its owners.<br>You must keep looking for Nanimon until you get the real treasure.",
		enemies:[],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Monzaemon"],
		fight:0,
		prosperityTrigger:0,
		prosperityPoints:1,
	},
	{
		recruited:false,
		name:"Ogremon1",
		level:"Champion",
		maps:[],
		recruitMap:"GCAN08_2",
		region:"Great Canyon Top Area",
		trigger:"Talk to Yuramon",
		location:"Between Monochrome Shop and Birdramon elevator.",
		requirement:"Once you've visited the Great Canyon (you need to trigger the textbox at the invisible bridge) talk to Yuramon and he'll tell something about bandits. Head back to the canyon and on the screen before the elevator chose the right path (screen has to be entered from Monochrome Shop side).<br />You'll encounter and fight Ogremon and 2 Agumon there.",
		unlocks:"Nothing",
		angemonTip:"If you fear danger, you'll lose sight of your goal. You gotta be brave enough to try climbing a dangerous cliff at least once.<br>Listen to anything you hear from the city about people who need help.",
		enemies:[
			{
				name:"Ogremon",
				hp:3600,
				mp:3500,
				off:450,
				def:260,
				spd:200,
				brn:150,
				bits:50,
				item:"HP Chip",
				dropChance:100,
				moves:[{name:"Magma Bomb",chance:42.86},{name:"Tremar",chance:57.14}],
				finisher:"Pummel Whack"
			},
			{
				name:"Agumon",
				hp:900,
				mp:1800,
				off:320,
				def:160,
				spd:90,
				brn:150,
				bits:300,
				item:"sm. recovery",
				dropChance:50,
				moves:[{name:"Spit Fire",chance:40},{name:"Fire Tower",chance:30},{name:"Magma Bomb",chance:20},{name:"Heat Laser",chance:10}],
				finisher:"Pepper Breath"
			},
			{
				name:"Agumon",
				hp:900,
				mp:1800,
				off:320,
				def:160,
				spd:90,
				brn:150,
				bits:300,
				item:"sm. recovery",
				dropChance:50,
				moves:[{name:"Spit Fire",chance:40},{name:"Fire Tower",chance:30},{name:"Magma Bomb",chance:20},{name:"Heat Laser",chance:10}],
				finisher:"Pepper Breath"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:6,
		prosperityPoints:0,
	},
	{
		recruited:false,
		name:"Ogremon2",
		level:"Champion",
		maps:[],
		recruitMap:"OGRE03",
		region:"Ogre Fortress",
		trigger:"Ogremon1",
		location:"Living Room",
		requirement:"Go to the elevator and chose DOWN and exit the screen on the bottom. You'll find Ogre Fortress there - enter it and in the last room you'll fight again against Ogremon and 2 Agumon.",
		unlocks:"Nothing",
		angemonTip:"",
		enemies:[
			{
				name:"Ogremon",
				hp:4000,
				mp:3500,
				off:480,
				def:270,
				spd:210,
				brn:150,
				bits:100,
				item:"HP Chip",
				dropChance:100,
				moves:[{name:"Dynamite Kick",chance:40},{name:"Tremar",chance:60}],
				finisher:"Pummel Whack"
			},
			{
				name:"Agumon",
				hp:1100,
				mp:2300,
				off:390,
				def:190,
				spd:80,
				brn:150,
				bits:400,
				item:"sm. recovery",
				dropChance:50,
				moves:[{name:"Spit Fire",chance:40},{name:"Fire Tower",chance:30},{name:"Magma Bomb",chance:20},{name:"Heat Laser",chance:10}],
				finisher:"Pepper Breath"
			},
			{
				name:"Agumon",
				hp:1100,
				mp:2300,
				off:390,
				def:190,
				spd:80,
				brn:150,
				bits:400,
				item:"sm. recovery",
				dropChance:50,
				moves:[{name:"Spit Fire",chance:40},{name:"Fire Tower",chance:30},{name:"Magma Bomb",chance:20},{name:"Heat Laser",chance:10}],
				finisher:"Pepper Breath"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Ogremon1"],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:0,
	},
	{
		recruited:false,
		name:"Ogremon3",
		level:"Champion",
		maps:[],
		recruitMap:"OGRE11",
		region:"Secret Beach Cave",
		trigger:"Ogremon2",
		location:"Second Screen in Secret Beach Cave",
		requirement:"Go to Freezeland and find Whamon. The Whamon recruitment is the whole phase. You'll fight against Ogremon, WaruSeadramon and Gabumon.",
		unlocks:"Nothing",
		angemonTip:"",
		enemies:[
			{
				name:"Ogremon",
				hp:4400,
				mp:3500,
				off:520,
				def:270,
				spd:250,
				brn:150,
				bits:100,
				item:"",
				dropChance:0,
				moves:[{name:"Magma Bomb",chance:42.86},{name:"Tremar",chance:57.14}],
				finisher:"Pummel Whack"
			},
			{
				name:"WaruSeadramon",
				hp:4500,
				mp:4600,
				off:560,
				def:280,
				spd:230,
				brn:100,
				bits:2800,
				item:"",
				dropChance:0,
				moves:[{name:"Giga Freeze",chance:44.44},{name:"Aurora Freeze",chance:33.33},{name:"Winter Blast",chance:22.22}],
				finisher:""
			},
			{
				name:"Gabumon",
				hp:1800,
				mp:1400,
				off:390,
				def:200,
				spd:70,
				brn:100,
				bits:100,
				item:"",
				dropChance:0,
				moves:[{name:"Dynamite Kick",chance:44.44},{name:"Megaton Punch",chance:44.44},{name:"War Cry",chance:11.11}],
				finisher:"Blue Blaster"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Ogremon2"],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:0,
	},
	{
		recruited:false,
		name:"Ogremon4",
		level:"Champion",
		maps:[],
		recruitMap:"TUNN02",
		region:"Drill Tunnel",
		trigger:"Ogremon3",
		location:"Hub screen",
		requirement:"Go to Freezeland and find Whamon. The Whamon recruitment is the whole phase. You'll fight against Ogremon, WaruSeadramon and Gabumon.<br />4. Go to the Drill Tunnel and in the hub you'll fight again against Ogremon and 2 Agumon. After that Ogremon will join the town.",
		unlocks:"Nothing",
		angemonTip:"There's a mean guy that has moved into a very populated area recently. Maybe it's... ",
		enemies:[
			{
				name:"Ogremon",
				hp:3600,
				mp:3500,
				off:450,
				def:260,
				spd:200,
				brn:150,
				bits:50,
				item:"HP Chip",
				dropChance:100,
				moves:[{name:"Magma Bomb",chance:42.86},{name:"Tremar",chance:57.14}],
				finisher:"Pummel Whack"
			},
			{
				name:"Agumon",
				hp:500,
				mp:800,
				off:180,
				def:100,
				spd:60,
				brn:150,
				bits:200,
				item:"sm. recovery",
				dropChance:50,
				moves:[{name:"Spit Fire",chance:60},{name:"Fire Tower",chance:40}],
				finisher:"Pepper Breath"
			},
			{
				name:"Agumon",
				hp:500,
				mp:800,
				off:180,
				def:100,
				spd:60,
				brn:150,
				bits:200,
				item:"sm. recovery",
				dropChance:50,
				moves:[{name:"Spit Fire",chance:60},{name:"Fire Tower",chance:40}],
				finisher:"Pepper Breath"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:["Ogremon3"],
		fight:1,
		prosperityTrigger:0,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Devimon",
		level:"Champion",
		maps:[],
		recruitMap:"MGEN06",
		region:"Mt. Infinity",
		trigger:"50pp",
		location:"6th level of Mt. Infinity",
		requirement:"win the fight against him",
		unlocks:"Secret shop - sells DV chips (massive stats gain, reduce lifetime by 24h)",
		angemonTip:"",
		enemies:[
			{
				name:"Devimon",
				hp:6800,
				mp:6000,
				off:780,
				def:550,
				spd:340,
				brn:250,
				bits:4800,
				item:"Quick Chip",
				dropChance:100,
				moves:[{name:"Megaton Punch",chance:30},{name:"War Cry",chance:30},{name:"Muscle Charge",chance:30},{name:"Megalo Spark",chance:10}],
				finisher:"Death Claw"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:50,
		prosperityPoints:2,
	},
	{
		recruited:false,
		name:"Megadramon",
		level:"Ultra",
		maps:[],
		recruitMap:"MGEN10",
		region:"Mt. Infinity",
		trigger:"50pp",
		location:"10th level of Mt. Infinity",
		requirement:"win the fight against him",
		unlocks:"?",
		angemonTip:"",
		enemies:[
			{
				name:"Megadramon",
				hp:7500,
				mp:8000,
				off:850,
				def:570,
				spd:450,
				brn:300,
				bits:5500,
				item:"Off. Chip",
				dropChance:100,
				moves:[{name:"Megaton Punch",chance:22.22},{name:"Giga Freeze",chance:38.89},{name:"DG Dimension",chance:38.89}],
				finisher:"Genoside Attack"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:50,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"MetalGreymon",
		level:"Ultra",
		maps:[],
		recruitMap:"MGEN98",
		region:"Mt. Infinity",
		trigger:"50pp",
		location:"11th level of Mt. Infinity",
		requirement:"win the fight against him",
		unlocks:"Gives your Digimon nicknames.",
		angemonTip:"",
		enemies:[
			{
				name:"MetalGreymon",
				hp:8600,
				mp:7800,
				off:900,
				def:620,
				spd:400,
				brn:300,
				bits:6200,
				item:"Def. Chip",
				dropChance:100,
				moves:[{name:"Inifinity Burn",chance:33.33},{name:"Meltdown",chance:33.33},{name:"Buster Dive",chance:33.33}],
				finisher:"Giga Scissor Claw"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:50,
		prosperityPoints:3,
	},
	{
		recruited:false,
		name:"Digitamamon",
		level:"Ultra",
		maps:[],
		recruitMap:"MGEN99",
		region:"Mt. Infinity",
		trigger:"50pp & beaten Machinedramon",
		location:"12th level of Mt. Infinity after you've beaten Machinedramon",
		requirement:"win the fight against him",
		unlocks:"Restaurant - allows Digitamamon glitch (eating food without hunger, allowing statsgain in no time)",
		angemonTip:"There are still some unknown Digimon, but finish your priority work first!<br>The last Digimon will be born at the last place you go to. Do you understand this?",
		enemies:[
			{
				name:"Digitamamon",
				hp:9999,
				mp:9999,
				off:999,
				def:720,
				spd:500,
				brn:700,
				bits:9999,
				item:"Quick Chip",
				dropChance:100,
				moves:[{name:"Meltdown",chance:37.5},{name:"Thunder Justice",chance:37.5},{name:"Confused Storm",chance:25}],
				finisher:"Nightmare Syndromer"
			}
		],
		recruitTriggerAnd:[],
		recruitTriggerOr:[],
		fight:1,
		prosperityTrigger:50,
		prosperityPoints:3,
	},
];
