const digimonStats = [
    {
        "id": 0,
        "name": "Hiro",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 1,
        "name": "Botamon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 2,
        "name": "Koromon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 3,
        "name": "Agumon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Heat Laser",
            "Red Inferno",
            "Sonic Jab",
            "Muscle Charge",
            "Pepper Breath",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 4,
        "name": "Betamon",
        "moves": [
            "Static Elect",
            "Electric Cloud",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Winter Blast",
            "Aqua Magic",
            "Electric Shock",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 5,
        "name": "Greymon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Prominence Beam",
            "Heat Laser",
            "Red Inferno",
            "Meltdown",
            "Dynamite Kick",
            "Counter",
            "Muscle Charge",
            "Megalo Spark",
            "Spinning Shot",
            "Mega Flame",
            "None",
            "None"
        ]
    },
    {
        "id": 6,
        "name": "Devimon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "War Cry",
            "Muscle Charge",
            "Megalo Spark",
            "Electric Cloud",
            "Spinning Shot",
            "Thunder Justice",
            "Giga Freeze",
            "Ice Statue",
            "Death Claw",
            "None",
            "None"
        ]
    },
    {
        "id": 7,
        "name": "Airdramon",
        "moves": [
            "Spit Fire",
            "Prominence Beam",
            "Heat Laser",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "Hurricane",
            "Spnning Needle",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 8,
        "name": "Tyrannomon",
        "moves": [
            "Spit Fire",
            "Prominence Beam",
            "Red Inferno",
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Blaze Blast",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 9,
        "name": "Meramon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Prominence Beam",
            "Heat Laser",
            "Red Inferno",
            "Inifinity Burn",
            "Dynamite Kick",
            "Counter",
            "War Cry",
            "Fireball",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 10,
        "name": "Seadramon",
        "moves": [
            "Spit Fire",
            "Magma Bomb",
            "Danger Sting",
            "Charm Perfume",
            "Poison Powder",
            "Tear Drop",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Winter Blast",
            "Aqua Magic",
            "Ice Blast",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 11,
        "name": "Numemon",
        "moves": [
            "Horizontal Kick",
            "Odor Spray",
            "Poop Spd Toss",
            "Big Poop Toss",
            "Poop Rnd Toss",
            "Rnd Spd Toss",
            "Big Rnd Toss",
            "Ult Poop Hell",
            "Party time",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 12,
        "name": "MetalGreymon",
        "moves": [
            "Heat Laser",
            "Inifinity Burn",
            "Meltdown",
            "Megaton Punch",
            "Buster Dive",
            "Tremar",
            "Power Crane",
            "Delete Program",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "All Range Beam",
            "DG Dimension",
            "Full Potential",
            "Giga Scissor Claw"
        ]
    },
    {
        "id": 13,
        "name": "Mamemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Power Crane",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "Full Potential",
            "Smiley Bomb",
            "None"
        ]
    },
    {
        "id": 14,
        "name": "Monzaemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Thunder Justice",
            "Confused Storm",
            "Lovely Attack",
            "None"
        ]
    },
    {
        "id": 15,
        "name": "Punimon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 16,
        "name": "Tsunomon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 17,
        "name": "Gabumon",
        "moves": [
            "Fire Tower",
            "Heat Laser",
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Tremar",
            "War Cry",
            "Blue Blaster",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 18,
        "name": "Elecmon",
        "moves": [
            "Dynamite Kick",
            "Counter",
            "Muscle Charge",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Wind Cutter",
            "Super Thunder Strike",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 19,
        "name": "Kabuterimon",
        "moves": [
            "Spit Fire",
            "Prominence Beam",
            "Red Inferno",
            "Wind Cutter",
            "Hurricane",
            "Poison Claw",
            "Danger Sting",
            "Green Trap",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "Electro Shocker",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 20,
        "name": "Angemon",
        "moves": [
            "Dynamite Kick",
            "Counter",
            "War Cry",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "Hurricane",
            "Hand of Fate",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 21,
        "name": "Birdramon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Prominence Beam",
            "Heat Laser",
            "Red Inferno",
            "Meltdown",
            "Wind Cutter",
            "Spinning Shot",
            "Hurricane",
            "Meteor Wing",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 22,
        "name": "Garurumon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Megaton Punch",
            "Buster Dive",
            "War Cry",
            "Giga Freeze",
            "Ice Needle",
            "Ice Statue",
            "Winter Blast",
            "Aqua Magic",
            "Howling Blaster",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 23,
        "name": "Frigimon",
        "moves": [
            "Sonic Jab",
            "Muscle Charge",
            "Tear Drop",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Ice Statue",
            "Winter Blast",
            "Aurora Freeze",
            "Aqua Magic",
            "Subzero Ice Punch",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 24,
        "name": "Whamon",
        "moves": [
            "Charm Perfume",
            "Poison Powder",
            "Tear Drop",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Ice Statue",
            "Winter Blast",
            "Aurora Freeze",
            "Aqua Magic",
            "Blasting Spout",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 25,
        "name": "Vegiemon",
        "moves": [
            "Poison Claw",
            "Danger Sting",
            "Green Trap",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "Water Blit",
            "Aqua Magic",
            "Sweet Breath",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 26,
        "name": "SkullGreymon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Giga Freeze",
            "Ice Statue",
            "Winter Blast",
            "Pulse Laser",
            "All Range Beam",
            "Dark Shot",
            "None"
        ]
    },
    {
        "id": 27,
        "name": "MetalMamemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Delete Program",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "All Range Beam",
            "Energy Bomb",
            "None"
        ]
    },
    {
        "id": 28,
        "name": "Vademon",
        "moves": [
            "Green Trap",
            "Bug",
            "Charm Perfume",
            "Power Crane",
            "Delete Program",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "All Range Beam",
            "DG Dimension",
            "Full Potential",
            "Abduction Beam",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 29,
        "name": "Poyomon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 30,
        "name": "Tokomon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 31,
        "name": "Patamon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Buster Dive",
            "War Cry",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "Boom Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 32,
        "name": "Kunemon",
        "moves": [
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Poison Claw",
            "Danger Sting",
            "Poison Powder",
            "Mass Morph",
            "Electric Thread",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 33,
        "name": "Unimon",
        "moves": [
            "Dynamite Kick",
            "Counter",
            "War Cry",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "Hurricane",
            "Aerial Attack",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 34,
        "name": "Ogremon",
        "moves": [
            "Spit Fire",
            "Magma Bomb",
            "Red Inferno",
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Poison Claw",
            "Insect Plague",
            "Pummel Whack",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 35,
        "name": "Shellmon",
        "moves": [
            "Charm Perfume",
            "Poison Powder",
            "Tear Drop",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Ice Statue",
            "Winter Blast",
            "Aurora Freeze",
            "Aqua Magic",
            "Hydro Pressure",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 36,
        "name": "Centarumon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Prominence Beam",
            "Heat Laser",
            "Red Inferno",
            "Meltdown",
            "Dynamite Kick",
            "Counter",
            "Muscle Charge",
            "Solar Ray",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 37,
        "name": "Bakemon",
        "moves": [
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Thunder Justice",
            "Hurricane",
            "Giga Freeze",
            "Winter Blast",
            "Aqua Magic",
            "Dark Claw",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 38,
        "name": "Drimogemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Green Trap",
            "Charm Perfume",
            "Drill Spin",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 39,
        "name": "Sukamon",
        "moves": [
            "Horizontal Kick",
            "Odor Spray",
            "Poop Spd Toss",
            "Big Poop Toss",
            "Poop Rnd Toss",
            "Rnd Spd Toss",
            "Big Rnd Toss",
            "Ult Poop Hell",
            "Party time",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 40,
        "name": "Andromon",
        "moves": [
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "Static Elect",
            "Megalo Spark",
            "Power Crane",
            "Delete Program",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "All Range Beam",
            "DG Dimension",
            "Full Potential",
            "Spiral Sword"
        ]
    },
    {
        "id": 41,
        "name": "Giromon",
        "moves": [
            "Megaton Punch",
            "Buster Dive",
            "Megalo Spark",
            "Electric Cloud",
            "Thunder Justice",
            "Power Crane",
            "Delete Program",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "All Range Beam",
            "DG Dimension",
            "Full Potential",
            "Deadly Bomb",
            "None"
        ]
    },
    {
        "id": 42,
        "name": "Etemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Megalo Spark",
            "Spinning Shot",
            "Thunder Justice",
            "Horizontal Kick",
            "Ult Poop Hell",
            "Dark Network & Concert Crush",
            "None"
        ]
    },
    {
        "id": 43,
        "name": "Yuramon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 44,
        "name": "Tanemon",
        "moves": [
            "Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 45,
        "name": "Biyomon",
        "moves": [
            "Spit Fire",
            "Heat Laser",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "Hurricane",
            "Spiral Twister",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 46,
        "name": "Palmon",
        "moves": [
            "Poison Claw",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "Tear Drop",
            "Water Blit",
            "Aqua Magic",
            "Poison Ivy",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 47,
        "name": "Monochromon",
        "moves": [
            "Spit Fire",
            "Prominence Beam",
            "Heat Laser",
            "Red Inferno",
            "Meltdown",
            "Megaton Punch",
            "Counter",
            "Tremar",
            "Green Trap",
            "Insect Plague",
            "Mass Morph",
            "Volcanic Strike",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 48,
        "name": "Leomon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Static Elect",
            "Megalo Spark",
            "Fist of the Beast King",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 49,
        "name": "Coelamon",
        "moves": [
            "Tear Drop",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Ice Statue",
            "Winter Blast",
            "Aqua Magic",
            "Poison Claw",
            "Danger Sting",
            "Insect Plague",
            "Variable Darts",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 50,
        "name": "Kokatorimon",
        "moves": [
            "Dynamite Kick",
            "Tremar",
            "War Cry",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "Hurricane",
            "Frozen Fire Shot",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 51,
        "name": "Kuwagamon",
        "moves": [
            "Sonic Jab",
            "Muscle Charge",
            "Wind Cutter",
            "Spinning Shot",
            "Poison Claw",
            "Danger Sting",
            "Green Trap",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "Scissor Claw",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 52,
        "name": "Mojyamon",
        "moves": [
            "Dynamite Kick",
            "Megaton Punch",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Winter Blast",
            "Aurora Freeze",
            "Aqua Magic",
            "Green Trap",
            "Mass Morph",
            "Bone Boomerang",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 53,
        "name": "Nanimon",
        "moves": [
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Horizontal Kick",
            "Odor Spray",
            "Poop Spd Toss",
            "Big Poop Toss",
            "Poop Rnd Toss",
            "Rnd Spd Toss",
            "Big Rnd Toss",
            "Party time",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 54,
        "name": "Megadramon",
        "moves": [
            "Dynamite Kick",
            "Megaton Punch",
            "Giga Freeze",
            "Winter Blast",
            "Ice Statue",
            "Power Crane",
            "Delete Program",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "All Range Beam",
            "DG Dimension",
            "Full Potential",
            "Genoside Attack",
            "None"
        ]
    },
    {
        "id": 55,
        "name": "Piximon",
        "moves": [
            "Poison Claw",
            "Danger Sting",
            "Green Trap",
            "Insect Plague",
            "Bug",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "Hurricane",
            "Bit Bomb",
            "None",
            "None"
        ]
    },
    {
        "id": 56,
        "name": "Digitamamon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Prominence Beam",
            "Heat Laser",
            "Red Inferno",
            "Inifinity Burn",
            "Meltdown",
            "Megalo Spark",
            "Spinning Shot",
            "Thunder Justice",
            "Confused Storm",
            "Hurricane",
            "Tear Drop",
            "Aqua Magic"
        ]
    },
    {
        "id": 57,
        "name": "Penguinmon",
        "moves": [
            "Poison Claw",
            "Charm Perfume",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Winter Blast",
            "Aqua Magic",
            "Super Slap",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 58,
        "name": "Ninjamon",
        "moves": [
            "Fire Tower",
            "Magma Bomb",
            "Sonic Jab",
            "Dynamite Kick",
            "Counter",
            "War Cry",
            "Danger Sting",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "Iga School Knife Throw",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 59,
        "name": "Phoenixmon",
        "moves": [
            "Magma Bomb",
            "Prominence Beam",
            "Red Inferno",
            "Inifinity Burn",
            "Meltdown",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Thunder Justice",
            "Confused Storm",
            "Hurricane",
            "Crimson Flare",
            "None"
        ]
    },
    {
        "id": 60,
        "name": "H-Kabuterimon",
        "moves": [
            "Prominence Beam",
            "Red Inferno",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Muscle Charge",
            "Poison Claw",
            "Danger Sting",
            "Green Trap",
            "Insect Plague",
            "Bug",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "Electro Shocker"
        ]
    },
    {
        "id": 61,
        "name": "MegaSeadramon",
        "moves": [
            "Tear Drop",
            "Giga Freeze",
            "Ice Needle",
            "Water Blit",
            "Ice Statue",
            "Winter Blast",
            "Aurora Freeze",
            "Aqua Magic",
            "Wind Cutter",
            "Confused Storm",
            "Hurricane",
            "Mail Strome",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 62,
        "name": "WereGarurumon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 63,
        "name": "Panjyamon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Static Elect",
            "Megalo Spark",
            "Fist of the Beast King",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 64,
        "name": "Gigadramon",
        "moves": [
            "Dynamite Kick",
            "Megaton Punch",
            "Giga Freeze",
            "Winter Blast",
            "Ice Statue",
            "Power Crane",
            "Delete Program",
            "Pulse Laser",
            "Reverse Prog",
            "Metal Sprinter",
            "All Range Beam",
            "DG Dimension",
            "Full Potential",
            "Genoside Attack",
            "None"
        ]
    },
    {
        "id": 65,
        "name": "MetalEtemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Counter",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "Muscle Charge",
            "Megalo Spark",
            "Spinning Shot",
            "Thunder Justice",
            "Horizontal Kick",
            "Ult Poop Hell",
            "Dark Network & Concert Crush",
            "None"
        ]
    },
    {
        "id": 66,
        "name": "Myotismon",
        "moves": [
            "Megaton Punch",
            "Thunder Justice",
            "Hurricane",
            "Giga Freeze",
            "Aurora Freeze",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 67,
        "name": "Yanmamon",
        "moves": [
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Danger Sting",
            "Insect Plague",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 68,
        "name": "Gotsumon",
        "moves": [
            "Megaton Punch",
            "Buster Dive",
            "Tremar",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 69,
        "name": "Flarerizamon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Heat Laser",
            "Red Inferno",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 70,
        "name": "WaruMonzaemon",
        "moves": [
            "Megaton Punch",
            "Buster Dive",
            "Muscle Charge",
            "Thunder Justice",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 71,
        "name": "SnowAgumon",
        "moves": [
            "Ice Needle",
            "Ice Statue",
            "Winter Blast",
            "Sonic Jab",
            "Muscle Charge",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 72,
        "name": "Hyogamon",
        "moves": [
            "Giga Freeze",
            "Ice Needle",
            "Sonic Jab",
            "Megaton Punch",
            "Buster Dive",
            "War Cry",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 73,
        "name": "PlatinumSukamon",
        "moves": [
            "Odor Spray",
            "Big Poop Toss",
            "Rnd Spd Toss",
            "Big Rnd Toss",
            "Ult Poop Hell",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 74,
        "name": "Dokunemon",
        "moves": [
            "Poison Claw",
            "Danger Sting",
            "Poison Powder",
            "Mass Morph",
            "Electric Thread",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 75,
        "name": "ShimaUnimon",
        "moves": [
            "Dynamite Kick",
            "Counter",
            "War Cry",
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 76,
        "name": "Tankmon",
        "moves": [
            "Spit Fire",
            "Red Inferno",
            "Megaton Punch",
            "Buster Dive",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 77,
        "name": "RedVegiemon",
        "moves": [
            "Poison Claw",
            "Danger Sting",
            "Green Trap",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 78,
        "name": "J-Mojyamon",
        "moves": [
            "Dynamite Kick",
            "Megaton Punch",
            "Water Blit",
            "Green Trap",
            "Mass Morph",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 79,
        "name": "NiseDrimogemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Counter",
            "Buster Dive",
            "Tremar",
            "Muscle Charge",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 80,
        "name": "Goburimon",
        "moves": [
            "Spit Fire",
            "Magma Bomb",
            "Sonic Jab",
            "Megaton Punch",
            "War Cry",
            "Giga Freeze",
            "Winter Blast",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 81,
        "name": "MudFrigimon",
        "moves": [
            "Sonic Jab",
            "Muscle Charge",
            "Tear Drop",
            "Water Blit",
            "Aqua Magic",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 82,
        "name": "Psychemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Tremar",
            "War Cry",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 83,
        "name": "ModokiBetamon",
        "moves": [
            "Static Elect",
            "Electric Cloud",
            "Water Blit",
            "Aqua Magic",
            "Electric Shock",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 84,
        "name": "ToyAgumon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Heat Laser",
            "Red Inferno",
            "Sonic Jab",
            "Muscle Charge",
            "Pepper Breath",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 85,
        "name": "Piddomon",
        "moves": [
            "Dynamite Kick",
            "Counter",
            "Megalo Spark",
            "Spinning Shot",
            "Confused Storm",
            "Hurricane",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 86,
        "name": "Aruraumon",
        "moves": [
            "Poison Claw",
            "Charm Perfume",
            "Poison Powder",
            "Tear Drop",
            "Water Blit",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 87,
        "name": "Geremon",
        "moves": [
            "Horizontal Kick",
            "Odor Spray",
            "Poop Spd Toss",
            "Poop Rnd Toss",
            "Rnd Spd Toss",
            "Party time",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 88,
        "name": "Vermilimon",
        "moves": [
            "Prominence Beam",
            "Heat Laser",
            "Red Inferno",
            "Meltdown",
            "Megaton Punch",
            "Counter",
            "Tremar",
            "Volcanic Strike",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 89,
        "name": "Fugamon",
        "moves": [
            "Spit Fire",
            "Magma Bomb",
            "Megaton Punch",
            "Static Elect",
            "Wind Cutter",
            "Hurricane",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 90,
        "name": "Tekkamon",
        "moves": [
            "Megaton Punch",
            "Buster Dive",
            "Reverse Prog",
            "Full Potential",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 91,
        "name": "MoriShellmon",
        "moves": [
            "Charm Perfume",
            "Poison Powder",
            "Tear Drop",
            "Water Blit",
            "Ice Statue",
            "Aqua Magic",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 92,
        "name": "Guardromon",
        "moves": [
            "Prominence Beam",
            "Megaton Punch",
            "Power Crane",
            "All Range Beam",
            "Full Potential",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 93,
        "name": "Muchomon",
        "moves": [
            "Poison Claw",
            "Giga Freeze",
            "Ice Needle",
            "Super Slap",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 94,
        "name": "Icemon",
        "moves": [
            "Megaton Punch",
            "Giga Freeze",
            "Ice Needle",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 95,
        "name": "Akatorimon",
        "moves": [
            "Dynamite Kick",
            "Static Elect",
            "Electric Cloud",
            "Wind Cutter",
            "Spinning Shot",
            "Confused Storm",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 96,
        "name": "Tsukaimon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Buster Dive",
            "War Cry",
            "Wind Cutter",
            "Spinning Shot",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 97,
        "name": "Sharmamon",
        "moves": [
            "Spit Fire",
            "Magma Bomb",
            "Sonic Jab",
            "Megaton Punch",
            "War Cry",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 98,
        "name": "ClearAgumon",
        "moves": [
            "Spit Fire",
            "Fire Tower",
            "Magma Bomb",
            "Heat Laser",
            "Red Inferno",
            "Sonic Jab",
            "Muscle Charge",
            "Pepper Breath",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 99,
        "name": "Weedmon",
        "moves": [
            "Poison Claw",
            "Danger Sting",
            "Green Trap",
            "Charm Perfume",
            "Poison Powder",
            "Mass Morph",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 100,
        "name": "IceDevimon",
        "moves": [
            "Sonic Jab",
            "Counter",
            "War Cry",
            "Giga Freeze",
            "Ice Statue",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 101,
        "name": "Darkrizamon",
        "moves": [
            "Magma Bomb",
            "Heat Laser",
            "Red Inferno",
            "Giga Freeze",
            "Ice Needle",
            "Winter Blast",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 102,
        "name": "SandYanmamon",
        "moves": [
            "Spit Fire",
            "Spinning Shot",
            "Hurricane",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 103,
        "name": "SnowGoburimon",
        "moves": [
            "Sonic Jab",
            "Megaton Punch",
            "War Cry",
            "Giga Freeze",
            "Winter Blast",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 104,
        "name": "BlueMeramon",
        "moves": [
            "Fire Tower",
            "Prominence Beam",
            "Red Inferno",
            "Dynamite Kick",
            "Counter",
            "Giga Freeze",
            "Ice Needle",
            "Ice Statue",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 105,
        "name": "Gururumon",
        "moves": [
            "Megaton Punch",
            "Buster Dive",
            "War Cry",
            "Giga Freeze",
            "Ice Statue",
            "Winter Blast",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 106,
        "name": "Saberdramon",
        "moves": [
            "Spit Fire",
            "Prominence Beam",
            "Red Inferno",
            "Wind Cutter",
            "Spinning Shot",
            "Hurricane",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 107,
        "name": "Soulmon",
        "moves": [
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "Thunder Justice",
            "Giga Freeze",
            "Dark Claw",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 108,
        "name": "Rockmon",
        "moves": [
            "Sonic Jab",
            "Muscle Charge",
            "Ice Needle",
            "Ice Statue",
            "Winter Blast",
            "Aurora Freeze",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 109,
        "name": "Otamamon",
        "moves": [
            "Tear Drop",
            "Water Blit",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 110,
        "name": "Gekomon",
        "moves": [
            "Tear Drop",
            "Giga Freeze",
            "Water Blit",
            "Winter Blast",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 111,
        "name": "Tentomon",
        "moves": [
            "Poison Claw",
            "Insect Plague",
            "Bug",
            "Charm Perfume",
            "Mass Morph",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 112,
        "name": "WaruSeadramon",
        "moves": [
            "Giga Freeze",
            "Aurora Freeze",
            "Winter Blast",
            "Confused Storm",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 113,
        "name": "Meteormon",
        "moves": [
            "Magma Bomb",
            "Meltdown",
            "Megaton Punch",
            "Tremar",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 114,
        "name": "",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 115,
        "name": "Machinedramon",
        "moves": [
            "Megaton Punch",
            "Megalo Spark",
            "Thunder Justice",
            "Aurora Freeze",
            "All Range Beam",
            "Full Potential",
            "Infinity Cannon",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 116,
        "name": "Analogman",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 117,
        "name": "Jijimon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 118,
        "name": "Market Manager",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 119,
        "name": "ShogunGekomon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 120,
        "name": "King of Sukamon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 121,
        "name": "Cherrymon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 122,
        "name": "Hagurumon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 123,
        "name": "Tinmon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 124,
        "name": "Master Tyrannomon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 125,
        "name": "Goburimon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 126,
        "name": "Brachiomon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 127,
        "name": "DemiMeramon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 128,
        "name": "Betamon",
        "moves": [
            "Static Elect",
            "Electric Cloud",
            "Water Blit",
            "Aqua Magic",
            "Electric Shock",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 129,
        "name": "Greymon",
        "moves": [
            "Magma Bomb",
            "Red Inferno",
            "Dynamite Kick",
            "Mega Flame",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 130,
        "name": "Devimon",
        "moves": [
            "Megaton Punch",
            "War Cry",
            "Muscle Charge",
            "Megalo Spark",
            "Thunder Justice",
            "Giga Freeze",
            "Ice Statue",
            "Death Claw",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 131,
        "name": "Airdramon",
        "moves": [
            "Megalo Spark",
            "Confused Storm",
            "Hurricane",
            "Spnning Needle",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 132,
        "name": "Tyrannomon",
        "moves": [
            "Megaton Punch",
            "Buster Dive",
            "Tremar",
            "War Cry",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 133,
        "name": "Meramon",
        "moves": [
            "Magma Bomb",
            "Heat Laser",
            "Dynamite Kick",
            "Fireball",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 134,
        "name": "Seadramon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 135,
        "name": "Numemon",
        "moves": [
            "Odor Spray",
            "Big Poop Toss",
            "Ult Poop Hell",
            "Party time",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 136,
        "name": "MetalGreymon",
        "moves": [
            "Inifinity Burn",
            "Meltdown",
            "Megaton Punch",
            "Buster Dive",
            "Reverse Prog",
            "DG Dimension",
            "Full Potential",
            "Giga Scissor Claw",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 137,
        "name": "Mamemon",
        "moves": [
            "Megaton Punch",
            "Buster Dive",
            "Metal Sprinter",
            "Full Potential",
            "Smiley Bomb",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 138,
        "name": "Monzaemon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 139,
        "name": "Gabumon",
        "moves": [
            "Dynamite Kick",
            "Megaton Punch",
            "Tremar",
            "War Cry",
            "Blue Blaster",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 140,
        "name": "Elecmon",
        "moves": [
            "Static Elect",
            "Megalo Spark",
            "Electric Cloud",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 141,
        "name": "Kabuterimon",
        "moves": [
            "Prominence Beam",
            "Danger Sting",
            "Charm Perfume",
            "Mass Morph",
            "Electro Shocker",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 142,
        "name": "Angemon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 143,
        "name": "Birdramon",
        "moves": [
            "Prominence Beam",
            "Red Inferno",
            "Hurricane",
            "Meteor Wing",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 144,
        "name": "Garurumon",
        "moves": [
            "Buster Dive",
            "War Cry",
            "Giga Freeze",
            "Ice Statue",
            "Howling Blaster",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 145,
        "name": "Frigimon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 146,
        "name": "Whamon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 147,
        "name": "Vegiemon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 148,
        "name": "SkullGreymon",
        "moves": [
            "Dynamite Kick",
            "Megaton Punch",
            "Buster Dive",
            "War Cry",
            "All Range Beam",
            "Dark Shot",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 149,
        "name": "MetalGreymon",
        "moves": [
            "Buster Dive",
            "Pulse Laser",
            "Metal Sprinter",
            "All Range Beam",
            "Energy Bomb",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 150,
        "name": "Vademon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 151,
        "name": "Patamon",
        "moves": [
            "Dynamite Kick",
            "Buster Dive",
            "Wind Cutter",
            "Spinning Shot",
            "Boom Bubble",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 152,
        "name": "Kunemon",
        "moves": [
            "Static Elect",
            "Electric Cloud",
            "Poison Claw",
            "Danger Sting",
            "Electric Thread",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 153,
        "name": "Unimon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 154,
        "name": "Ogremon",
        "moves": [
            "Magma Bomb",
            "Dynamite Kick",
            "Tremar",
            "Pummel Whack",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 155,
        "name": "Shellmon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 156,
        "name": "Centarumon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 157,
        "name": "Bakemon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 158,
        "name": "Drimogemon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "Megaton Punch",
            "Tremar",
            "Drill Spin",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 159,
        "name": "Sukamon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 160,
        "name": "Andromon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 161,
        "name": "Giromon",
        "moves": [
            "Power Crane",
            "Delete Program",
            "Reverse Prog",
            "DG Dimension",
            "Deadly Bomb",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 162,
        "name": "Etemon",
        "moves": [
            "Dynamite Kick",
            "Buster Dive",
            "War Cry",
            "Spinning Shot",
            "Dark Network & Concert Crush",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 163,
        "name": "Biyomon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 164,
        "name": "Palmon",
        "moves": [
            "Poison Claw",
            "Poison Powder",
            "Water Blit",
            "Poison Ivy",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 165,
        "name": "Monochromon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 166,
        "name": "Leomon",
        "moves": [
            "Sonic Jab",
            "Dynamite Kick",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 167,
        "name": "Coelamon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 168,
        "name": "Kokatorimon",
        "moves": [
            "Dynamite Kick",
            "War Cry",
            "Megalo Spark",
            "Confused Storm",
            "Frozen Fire Shot",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 169,
        "name": "Kuwagamon",
        "moves": [
            "Sonic Jab",
            "Muscle Charge",
            "Spinning Shot",
            "Poison Claw",
            "Poison Powder",
            "Scissor Claw",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 170,
        "name": "Mojyamon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 171,
        "name": "Nanimon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 172,
        "name": "Megadramon",
        "moves": [
            "Megaton Punch",
            "Giga Freeze",
            "DG Dimension",
            "Genoside Attack",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 173,
        "name": "Piximon",
        "moves": [
            "Danger Sting",
            "Bug",
            "Confused Storm",
            "Bit Bomb",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 174,
        "name": "Digitamamon",
        "moves": [
            "Meltdown",
            "Thunder Justice",
            "Confused Storm",
            "Nightmare Syndromer",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 175,
        "name": "Ninjamon",
        "moves": [
            "Magma Bomb",
            "Dynamite Kick",
            "Charm Perfume",
            "Iga School Knife Throw",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 176,
        "name": "Penguinmon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 177,
        "name": "Myotismon",
        "moves": [
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None",
            "None"
        ]
    },
    {
        "id": 178,
        "name": "Greymon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    },
    {
        "id": 179,
        "name": "MetalGreymon",
        "moves": [
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower",
            "Fire Tower"
        ]
    }
];